### Realiza a segmentação do que deve ser Faturado ou não ###

In [0]:
%run "/Workspace/Jurídico/Normalizador_de_dados/Normalizador"

### Normalizar e importar as Bibliotecas necessárias para as automações###

Collecting pyxlsb
  Obtaining dependency information for pyxlsb from https://files.pythonhosted.org/packages/7e/92/345823838ae367c59b63e03aef9c331f485370f9df6d049256a61a28f06d/pyxlsb-1.0.10-py2.py3-none-any.whl.metadata
  Downloading pyxlsb-1.0.10-py2.py3-none-any.whl.metadata (2.5 kB)
Downloading pyxlsb-1.0.10-py2.py3-none-any.whl (23 kB)
Installing collected packages: pyxlsb
Successfully installed pyxlsb-1.0.10
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

Collecting unidecode
  Obtaining dependency information for unidecode from https://files.pythonhosted.org/packages/8f/b7/559f59d57d18b44c6d1250d2eeaa676e028b9c527431f5d0736478a73ba1/Unidecode-1.4.0-py3-none-any.whl.metadata
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/235.8 kB ? eta -:--:--
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 235.5/235.8 kB 7.2 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 5.8 MB/s eta 0:00:00
Installing collected packages: unidecode
Successfully installed unidecode-1.4.0
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

Collecting xlwings
  Obtaining dependency information for xlwings from https://files.pythonhosted.org/packages/10/d1/be9425cedaa84fe9eaadca61878bf03c7127798f059545718143f8b54dce/xlwings-0.33.20-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading xlwings-0.33.20-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.3 kB)
Downloading xlwings-0.33.20-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/1.4 MB ? eta -:--:--
   ━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.2/1.4 MB 6.6 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 1.4/1.4 MB 21.7 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 17.3 MB/s eta 0:00:00
Installing collected packages: xlwings
Successfully installed xlwings-0.33.20
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

Collecting xlsxwriter
  Obtaining dependency information for xlsxwriter from https://files.pythonhosted.org/packages/3a/0c/3662f4a66880196a590b202f0db82d919dd2f89e99a27fadef91c4a33d41/xlsxwriter-3.2.9-py3-none-any.whl.metadata
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/175.3 kB ? eta -:--:--
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 174.1/175.3 kB 5.8 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 4.6 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.9
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

Collecting openpyxl
  Obtaining dependency information for openpyxl from https://files.pythonhosted.org/packages/c0/da/977ded879c29cbd04de313843e76868e6e13408a94ed6b987245dc7c8506/openpyxl-3.1.5-py2.py3-none-any.whl.metadata
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Obtaining dependency information for et-xmlfile from https://files.pythonhosted.org/packages/c1/8b/5fe2cc11fee489817272089c4203e679c63b570a5aaeb18d852ae3cbba6a/et_xmlfile-2.0.0-py3-none-any.whl.metadata
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/250.9 kB ? eta -:--:--
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━ 225.3/250.9 kB 7.0 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.9/250.9 kB 5.9 MB/s eta 0:00:00
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

Requirement already satisfied: openpyxl in /local_disk0/.ephemeral_nfs/envs/pythonEnv-593e336b-9b58-495d-9ec0-34f284c631fc/lib/python3.11/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /local_disk0/.ephemeral_nfs/envs/pythonEnv-593e336b-9b58-495d-9ec0-34f284c631fc/lib/python3.11/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

✅ Bibliotecas importadas e configurações aplicadas com sucesso!

Requirement already satisfied: openpyxl in /local_disk0/.ephemeral_nfs/envs/pythonEnv-593e336b-9b58-495d-9ec0-34f284c631fc/lib/python3.11/site-packages (3.1.5)
Requirement already satisfied: unidecode in /local_disk0/.ephemeral_nfs/envs/pythonEnv-593e336b-9b58-495d-9ec0-34f284c631fc/lib/python3.11/site-packages (1.4.0)
Collecting xlrd
  Obtaining dependency information for xlrd from https://files.pythonhosted.org/packages/1a/62/c8d562e7766786ba6587d09c5a8ba9f718ed3fa8af7f4553e8f91c36f302/xlrd-2.0.2-py2.py3-none-any.whl.metadata
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: et-xmlfile in /local_disk0/.ephemeral_nfs/envs/pythonEnv-593e336b-9b58-495d-9ec0-34f284c631fc/lib/python3.11/site-packages (from openpyxl) (2.0.0)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/96.6 kB ? eta -:--:--
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 3.3 MB/s eta 0:00:00
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

Exemplo informado

In [0]:
dbutils.widgets.text("Mes", "", "Data Bases Ativo e Encerrrado")
Mes = dbutils.widgets.get("Mes")

In [0]:
base_ger = f'/Volumes/databox/juridico_comum/arquivos/financeiro/Faturamento_Civel/Base_Final_Mensal/CIVEL_GERENCIAL - {Mes}.xlsx'
base_ac = f'/Volumes/databox/juridico_comum/arquivos/financeiro/Faturamento_Civel/Base_Aceite_Mensal/Data Aceite - Consolidada.xlsx'
base_fatu = f'/Volumes/databox/juridico_comum/arquivos/financeiro/Faturamento_Civel/Faturamento_honoararios_2023 - 2025/Consolidado Faturamento Honorários Cível Massa 2023 e 2025.xlsx'
base_zurick = f'/Volumes/databox/juridico_comum/arquivos/financeiro/Faturamento_Civel/Base_Zurick/PJ - REGRAS DO FLUXO DE CADASTRO CÍVEL MASSA - {Mes}.xlsx'

In [0]:
df_ger = pd.read_excel(
    base_ger,
    sheet_name='CÍVEL',
    header=5
)

df_ac = pd.read_excel(
    base_ac,
    sheet_name='ACEITE DE PATROCÍNIO E DESCREDE',
    header=5
)

#df_fatu_hist = pd.read_excel(
 #   base_fatu,
  #  sheet_name='Contrato Novo',
   # header=1
#)

df_fatu_hist_old = pd.read_excel(
    base_fatu,
    sheet_name='Contrato Antigo',
    header=1
)

In [0]:
df_id_zurick = pd.read_excel(
    base_zurick,
    sheet_name='REGRAS DO FLUXO DE CAD CIVEL',
    header=5
)

In [0]:
# 1. Defina as condições
condicao_1 = df_ger['TERCEIRO SOLVENTE'] == 'ZURICH'
#condicao_2 = df_ger['OUTRAS PARTES / NÃO-CLIENTES'].str.contains('ZURICH', na=False)

# 2. Aplique o filtro usando .loc 
df_zurich = df_ger.loc[condicao_1].copy()

# 3. Verifique
df_zurich.head()

,PROCESSO - ID,PASTA,GRUPO,ÁREA DO DIREITO,SUB-ÁREA DO DIREITO,ESTEIRA,ASSUNTO (CÍVEL) - PRINCIPAL,ASSUNTO (CÍVEL) - ASSUNTO,DATA REGISTRADO,STATUS,CENTRO DE CUSTO / ÁREA DEMANDANTE - CÓDIGO,EMPRESA,ADVOGADO RESPONSÁVEL,VALOR DA CAUSA,ESFERA,ESTADO,COMARCA,FORO/TRIBUNAL/ÓRGÃO,VARA/ÓRGÃO,AÇÃO,DISTRIBUIÇÃO,NÚMERO DO PROCESSO,PARTE CONTRÁRIA NOME,PARTE CONTRÁRIA CPF,ESCRITÓRIO EXTERNO,Escritório Anterior,FASE,COMPRA DIRETA OU MARKETPLACE? - NEW,USUÁRIO CADASTRANTE,DATA DA BAIXA PROVISÓRIA,DATA DA REATIVAÇÃO,VALOR PROVISIONADO,VALOR PROVISIONADO ATUALIZADO,PROCESSO CRITICO? (CÍVEL),ASSISTENTE JURÍDICO - CÍVEL,ASSISTENTE JURÍDICO -,DATA AUDIENCIA INICIAL,RECLAMAÇÃO BLACK FRIDAY?,OUTRAS PARTES / NÃO-CLIENTES,MOTIVO DA CRITICIDADE,ADVOGADO DA PARTE CONTRÁRIA,DATA DE REABERTURA,DATA DE RECEBIMENTO,PARTE DESCRITA NA INICIAL,TIPO DE CONTINGÊNCIA,ANO DA BLACK FRIDAY,DATA DA ÚLTIMA MOVIMENTAÇÃO PROCESSUAL,OBSERVAÇÕES,OBSERVAÇÃO,TERCEIRO SOLVENTE,INCONTROVERSO (ZERAR PROVISÃO),RESULTADO,DATA DE SOLICITAÇÃO DE ENCERRAMENTO,DATA DE ENCERRAMENTO NO TRIBUNAL,MOTIVO DE ENCERRAMENTO,RECLAMAÇÃO ANTERIOR NO PROCON?,DATA DE REGISTRO DO ENCERRAMENTO,EXISTE PROCESSO COM O MESMO CPF?,CÍVEL MASSA - RESPONSABILIDADE,ESTRATÉGIA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,JUSTIFICATIVA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,CÍVEL MASSA - TIPOS DE TERCEIRO,PARTE CONTRÁRIA DATA ADMISSÃO,PARTE CONTRÁRIA DATA DISPENSA,PARTE CONTRÁRIA - STATUS EM FOLHA,PARTE CONTRÁRIA - MATRICULA,PARTE CONTRÁRIA - CARGO - CARGO (GRUPO),MOTIVO DA BAIXA PROVISÓRIA,PRODUTO,FABRICANTE DO PRODUTO,VALOR DO PRODUTO,PROCESSO - Nº. PEDIDO,DATA DO PEDIDO,LISTA LOJISTA - NOME,LISTA LOJISTA - ID,DATA DA COMPRA,TRANSPORTADORA,NÚMERO DA NOTA FISCAL,SITE DA COMPRA,DATA DO FATO GERADOR,DATA FATO GERADOR,DATA DO FATO GERADOR.1,DATA DO FATO GERADOR.2,INDIQUE A FILIAL,Data da Baixa Provisória,DATA DE REATIVAÇÃO - nativo,DATA DA REATIVAÇÃO -,E-MAIL - PARTE CONTRÁRIA,Processo - RESPONSÁVEL PELA VALIDAÇÃO - AUTOMÁTICO,Processo - RESPONSÁVEL PELA VALIDAÇÃO - MANUAL,PARA QUAL STATUS DESEJA ALTERAR?,MOTIVO DA ALTERAÇÃO DE STATUS,APTO PARA ACORDO?,ILEGITIMIDADE PASSIVA,PROJETO RECORTE MASSA?,Processo - EVENTO - CÍVEL,Processo - POSSUI A INICIAL?,Processo - CARTEIRA ESTRATÉGICO - CIVEL,Processo - MOTIVO DA APTIDÃO ?,PROCESSO - VIA NO POLO,PROCESSO - OBJETO CÍVEL (2) - NEW - SECUNDÁRIO,PROCESSO - OBJETO CÍVEL (2) - NEW - ASSUNTO,FEIRÃO LIMPA NOME,DESENROLA BRASIL,SUBSÍDIOS DISPONIBILIZADOS ATÉ O MOMENTO DE INSERÇÃO DA DEFESA?,APRESENTADA DEFESA GENÉRICA?,CATEGORIZAÇÃO BANQI,GRUPO CASAS BAHIA NO POLO DA AÇÃO?,Processo - DATA DA ABERTURA DE CONTA,PAGAR HONORÁRIOS AO ESCRITÓRIO?,Pedido,ADVOGADO OFENSOR (CÍV. MASSA),CÍVEL MASSA - FLUXO DE RESSARCIMENTO?
138,298257,JEC.199637,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),VÍCIO DO PRODUTO,PRODUTO DE TERCEIROS,2015-11-23,BAIXA PROVISORIA,2112003054.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,28509.00,JUDICIAL,RJ,CAMPOS DOS GOYTACAZES,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,4ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2015-11-05,0041654-95.2015.8.19.0014,LUIZ CARLOS PESSANHA,473.509.467-91,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,CUMPRIMENTO DE SENTENÇA,DIRETA,GUILHERME SPAMER,2024-06-28 20:51:58.858,NaT,0,0.00,NÃO,YASMIN BARBOSA VICENTINI,RAFAEL EPISCOPO RODRIGUES COSTA,NaN,NÃO,TERCEIRO - ZURICH MINAS BRASIL SEGUROS S/A CONTINENTAL LTDA,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,2018-07-27 16:02:33.797,2019-08-07,NOVA CASA BAHIA S/A (CASAS BAHIA),PASSIVO,NaN,2017-04-26,NaN,PROCESSOS ENCERRADOS POR BANCO CONFORME ANALISE FEITA EM PLANILHA ENVIADA A GERENCIA DO PLANEJAM...,ZURICH,NaN,PARCIALMENTE PROCEDENTE,2018-08-24,2020-11-04,CONDENAÇÃO COM OBF E PAGAMENTO,NÃO,2020-11-04,NaN,SOLIDÁRIA,ACORDO,DECISÃO DESFAVORÁVEL,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,GELADEIRA,NI,0.00,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2024-06-28 20:51:58.858,NaN,NaT,NaN,NaN,NaN,2 - DE ENCERRADO PARA BAIXA PROVISÓRIA,CUSTAS REMANESCENTE,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NÃO SE APLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
734,620996,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),VÍCIO DO PRODUTO,PRODUTO DE TERCEIROS,2017-07-24,ATIVO,2112003054.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,15000.00,JUDICIAL,RJ,SÃO GONÇALO,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,8ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2017-07-05,0056557-34.2016.8.19.0004,IVONETE ALMEIDA ALVES,720.271.697-68,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,CONHECIMENTO,NaN,GABRIELLE F MALPELLI,NaT,NaT,3168,5069.59,NÃO,NAYARA CARLA DE SOUSA,LEONARDO PAULO LOMBARDI RODRIGUES - CNOVA,NaN,NÃO,NaN,NaN,EMERSON DE OLIVEIRA MARINS,NaT,2017-07-18,NaN,PASSIVO,NaN,NaT,NaN,NaN,ZURICH,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NÃO,SOLIDÁRIA,DEFESA,RESPONSABILIDADE DE TERCEIRO,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,COLCHÃO,CASTOR COLCHÕES,0.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,SEGURO,NÃO ATENDIMENTO AO CONSUMIDOR,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
749,565741,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),GARANTIA ESTENDIDA,NÃO ATENDIMENTO AO CONSUMIDOR -GE,2017-02-16,ATIVO,2106500768.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,15522.00,JUDICIAL,RJ,NITERÓI,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,9ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-03-29,0035236-46.2016.8.19.0002,ANDRE ESTABILA NOGUEIRA,012.882.487-50,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,CUMPRIMENTO DE SENTENÇA,DIRETA,JHONATAS.MELO,NaT,NaT,1854,2966.86,NÃO,YASMIN BARBOSA VICENTINI,RAFAEL EPISCOPO RODRIGUES COSTA,NaN,NÃO,"TERCEIRO - ZURICH MINAS BRASIL SEGUROS S.A, TERCEIRO - ALCATEL-LUCENT BRASIL S/A",NaN,MARCIA SOUZA - 186764,NaT,2017-02-07,NaN,PASSIVO,NaN,NaT,NaN,NaN,ZURICH,SIM,NaN,NaT,NaT,NaN,NaN,NaT,NÃO,SOLIDÁRIA,ACORDO,DECISÃO DESFAVORÁVEL,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,ESTRATÉGIA,SIM,NÃO SE APLICA,NÃO SE APLICA,NÃO,NÃO,NaN,NaN,NaN,SIM,NaN,NaN,"DANOS MATERIAIS, DANOS MATERIAIS, DANOS MORAIS, DANOS MORAIS",NaN,NaN
815,641644,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),GARANTIA ESTENDIDA,NÃO ATENDIMENTO AO CONSUMIDOR -GE,2017-10-06,ATIVO,2106500768.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,7283.00,JUDICIAL,RJ,RIO DE JANEIRO - CAMPO GRANDE,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,1ª VARA CÍVEL,AÇÃO DE RESCISÃO CONTRATUAL,2017-09-11,00316694320178190205,VANDA CARLOTA FERREIRA,081.539.947-27,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,RECURSAL (TJ),DIRETA,YASMIN BARBOSA VICENTINI,NaT,NaT,1854,2966.86,NÃO,YASMIN BARBOSA VICENTINI,RAFAEL EPISCOPO RODRIGUES COSTA,NaN,NÃO,"TERCEIRO - BSH CONTINENTAL ELETRODOMÉSTICO LTDA, TERCEIRO - ZURICH MINAS BRASIL SEGURO S/A",NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,2017-10-04,NaN,PASSIVO,NaN,NaT,NaN,NaN,ZURICH,NaN,NaN,NaT,NaT,NaN,NÃO,NaT,NaN,SOLIDÁRIA,DEFESA,SUBSÍDIOS FAVORÁVEIS,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,NaN,NaN,NaN,ESTRATÉGIA,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM
972,653245,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),GARANTIA ESTENDIDA,NÃO ATENDIMENTO AO CONSUMIDOR -GE,2017-11-21,ATIVO,2106500768.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,9370.00,JUDICIAL,RJ,RIO DE JANEIRO - SANTA CRUZ,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,2ª VARA CÍVEL,AÇÃO DE RESCISÃO CONTRATUAL,2017-08-09,00029184320178190206,KELEI DE FREITAS CORREIA,997.452.087-87,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,CONHECIMENTO,DIRETA,JOÃO PAULO TABAI DE JESUS,NaT,NaT,0,0.00,NÃO,YASMIN BARBOSA VICENTINI,RAFAEL EPISCOPO RODRIGUES COSTA,NaN,NÃO,"RÉU - INDUSTRIA DE MOVEIS BARTIRA LTDA , RÉU - ZURICH MINAS BRASIL SEGUROS S.A",NaN,DEFENSORIA PUBLICA DO ESTADO DO RIO DE JANEIRO,NaT,2017-09-22,NaN,PASSIVO,NaN,NaT,NaN,NaN,ZURICH,NaN,NaN,NaT,NaT,NaN,NÃO,NaT,NaN,TERCEIROS,DEFESA,SUBSÍDIOS FAVORÁVEIS,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,GUARDA ROUPA,BARTIRA,399.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,2015-11-27,NaN,NaN,NaN,NaN,2015-11-27,NaT,NaN,NaN,NaT,NaN,NaT,NaN,ROBERTA LUANA ROCHA,ROBERTA LUANA ROCHA,NaN,NaN,NÃO,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM

In [0]:
df_id_zurick.head()

,ID DO PROCESSO,NÚMERO DO PROCESSO,SUB-ÁREA DO DIREITO,STATUS,DATA REGISTRADO,COMPRA DIRETA OU MARKETPLACE? - NEW,TERCEIRO SOLVENTE,OBJETO CÍVEL (1) - PRINCIPAL,OBJETO CÍVEL (1) - ASSUNTO,TIPOS DE TERCEIRO,RESPONSABILIDADE,ESTRATÉGIA,JUSTIFICATIVA,WF DE TERCEIRO,ESCRITÓRIO,ADVOGADO RESPONSÁVEL,CESSÃO DE CRÉDITO,ESTADO,COMARCA,EMPRESA,PAGAMENTOS,MATRIZ CARTÃO,MATRIZ FORNECEDOR,MATRIZ MARKETPLACE,MATRIZ SEGURO OU SERVIÇO,MATRIZ SEGURO,MATRIZ SERVIÇO,MATRIZ LIVELO,MATRIZ VIA OUT,MATRIZ SICREDI,MATRIZ BANCO INTER,PROCESSO - CÍVEL MASSA - TIPOS DE TERCEIRO,MODALIDADE DE NEGÓCIO,FLUXO DE RESSARCIMENTO?,PARCEIRO NO POLO?,PAGAR HONORÁRIOS AO ESCRITÓRIO?,OUTRAS PARTES / NÃO-CLIENTES
0,1147921,0198407-65.2022.8.05.0001,JEC,ENCERRADO,2023-01-05 16:31:57.742,DIRETA,ITAPEVA,VENDA DE CARTEIRA DE CRÉDITO,VENDA DE CARTEIRA DE CRÉDITO - VCC,VENDA DE CARTEIRA DE CRÉDITO,CASAS BAHIA,DEFESA,AUDIÊNCIA INICIAL MAIOR QUE 30 DIAS OU NÃO CADASTRADA,"AUD +30/VAZIA - SIM - CIÊNCIA DE AÇÃO ENVOLVENDO TERCEIRO, DEFINIÇÃO DE ESTRATÉGIA E RESPONSABIL...","FREIRE, GERBASI, BITTENCOURT E MACEDO",ANNA KAROLYNE GOMES DE OLIVEIRA ABADE,SIM,BA,SALVADOR,GRUPO CASAS BAHIA S/A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VENDA DE CARTEIRA DE CRÉDITO,NaN,NaN,NaN,NaN,RÉU - ITAPEVA XI FUNDO DE INV EM DIREITO
1,1147920,0197744-19.2022.8.05.0001,JEC,ENCERRADO,2023-01-05 16:17:13.143,DIRETA,ITAPEVA,VENDA DE CARTEIRA DE CRÉDITO,VENDA DE CARTEIRA DE CRÉDITO - VCC,VENDA DE CARTEIRA DE CRÉDITO,CASAS BAHIA,DEFESA,AUDIÊNCIA INICIAL MAIOR QUE 30 DIAS OU NÃO CADASTRADA,"AUD +30/VAZIA - SIM - CIÊNCIA DE AÇÃO ENVOLVENDO TERCEIRO, DEFINIÇÃO DE ESTRATÉGIA E RESPONSABIL...","FREIRE, GERBASI, BITTENCOURT E MACEDO",BRUNA CATANANTE BENITES,SIM,BA,SALVADOR,GRUPO CASAS BAHIA S/A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VENDA DE CARTEIRA DE CRÉDITO,NaN,NaN,NaN,NaN,RÉU - ITAPEVA XI FUNDO DE INV EM DIREITO
2,1147923,0197873-24.2022.8.05.0001,JEC,ENCERRADO,2023-01-05 16:39:17.238,DIRETA,ITAPEVA,VENDA DE CARTEIRA DE CRÉDITO,VENDA DE CARTEIRA DE CRÉDITO - VCC,VENDA DE CARTEIRA DE CRÉDITO,CASAS BAHIA,DEFESA,AUDIÊNCIA INICIAL MAIOR QUE 30 DIAS OU NÃO CADASTRADA,"AUD +30/VAZIA - SIM - CIÊNCIA DE AÇÃO ENVOLVENDO TERCEIRO, DEFINIÇÃO DE ESTRATÉGIA E RESPONSABIL...","FREIRE, GERBASI, BITTENCOURT E MACEDO",BRUNA CATANANTE BENITES,SIM,BA,SALVADOR,GRUPO CASAS BAHIA S/A,"CONDENAÇÃO - CÍVEL MASSA - 25/04/2023 - PAGAMENTO CONDENAÇÃO DANO MORAL. - 3.109,78\n",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VENDA DE CARTEIRA DE CRÉDITO,NaN,NaN,NaN,NaN,RÉU - ITAPEVA XI FUNDO DE INV EM DIREITO
3,1147929,0002846-69.2022.8.05.0271,JEC,ENCERRADO,2023-01-05 17:22:25.858,DIRETA,ITAPEVA,VENDA DE CARTEIRA DE CRÉDITO,VENDA DE CARTEIRA DE CRÉDITO - VCC,VENDA DE CARTEIRA DE CRÉDITO,CASAS BAHIA,DEFESA,AUDIÊNCIA INICIAL MAIOR QUE 30 DIAS OU NÃO CADASTRADA,"AUD +30/VAZIA - SIM - CIÊNCIA DE AÇÃO ENVOLVENDO TERCEIRO, DEFINIÇÃO DE ESTRATÉGIA E RESPONSABIL...",QUEIROZ CAVALCANTI ADVOGADOS,JESSYCA DE OLIVEIRA DE ARAUJO,SIM,BA,VALENÇA,GRUPO CASAS BAHIA S/A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VENDA DE CARTEIRA DE CRÉDITO,NaN,NaN,NaN,NaN,RÉU - ITAPEVA XI FUNDO DE INV EM DIREITO
4,1147930,0197697-45.2022.8.05.0001,JEC,ENCERRADO,2023-01-05 17:29:36.841,DIRETA,ITAPEVA,VENDA DE CARTEIRA DE CRÉDITO,VENDA DE CARTEIRA DE CRÉDITO - VCC,VENDA DE CARTEIRA DE CRÉDITO,CASAS BAHIA,DEFESA,AUDIÊNCIA INICIAL MAIOR QUE 30 DIAS OU NÃO CADASTRADA,"AUD +30/VAZIA - SIM - CIÊNCIA DE AÇÃO ENVOLVENDO TERCEIRO, DEFINIÇÃO DE ESTRATÉGIA E RESPONSABIL...",QUEIROZ CAVALCANTI ADVOGADOS,JESSYCA DE OLIVEIRA DE ARAUJO,SIM,BA,SALVADOR,GRUPO CASAS BAHIA S/A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VENDA DE CARTEIRA DE CRÉDITO,NaN,NaN,NaN,NaN,RÉU - ITAPEVA XI FUNDO DE INV EM DIREITO

In [0]:
df_zurich = df_zurich.merge(
    df_id_zurick[['ID DO PROCESSO', 'MATRIZ SEGURO']], 
    left_on='PROCESSO - ID',
    right_on='ID DO PROCESSO',
    how='left'
)

df_zurich = df_zurich.drop(columns=['ID DO PROCESSO'])

In [0]:
nao_pagar = 	    ['PARCEIRO - CONSUMIDOR NÃO ACEITA REPARO OU RECUSA INDENIZAÇÃO','PARCEIRO - DEMORA NA REGULAÇÃO DO SINISTRO',
				    'PARCEIRO - INDENIZAÇÃO INDEVIDA OU INSUFICIENTE DO SINISTRO', 'PARCEIRO - LIMITAÇÃO INDEVIDA DE COBERTURAS DO SEGURO (EX. FURTO QUALIFICADO)',
				    'PARCEIRO - RECUSA OU ATENDIMENTO INADEQUADO DO SINISTRO']

condz1 = df_zurich['MATRIZ SEGURO'].isin(nao_pagar)

df_zurich['SEGUIR COM O PAGAMENTO DE HONORARIOS'] = np.where(condz1, 'NÃO', '')

In [0]:
df_zurich.head()

,PROCESSO - ID,PASTA,GRUPO,ÁREA DO DIREITO,SUB-ÁREA DO DIREITO,ESTEIRA,ASSUNTO (CÍVEL) - PRINCIPAL,ASSUNTO (CÍVEL) - ASSUNTO,DATA REGISTRADO,STATUS,CENTRO DE CUSTO / ÁREA DEMANDANTE - CÓDIGO,EMPRESA,ADVOGADO RESPONSÁVEL,VALOR DA CAUSA,ESFERA,ESTADO,COMARCA,FORO/TRIBUNAL/ÓRGÃO,VARA/ÓRGÃO,AÇÃO,DISTRIBUIÇÃO,NÚMERO DO PROCESSO,PARTE CONTRÁRIA NOME,PARTE CONTRÁRIA CPF,ESCRITÓRIO EXTERNO,Escritório Anterior,FASE,COMPRA DIRETA OU MARKETPLACE? - NEW,USUÁRIO CADASTRANTE,DATA DA BAIXA PROVISÓRIA,DATA DA REATIVAÇÃO,VALOR PROVISIONADO,VALOR PROVISIONADO ATUALIZADO,PROCESSO CRITICO? (CÍVEL),ASSISTENTE JURÍDICO - CÍVEL,ASSISTENTE JURÍDICO -,DATA AUDIENCIA INICIAL,RECLAMAÇÃO BLACK FRIDAY?,OUTRAS PARTES / NÃO-CLIENTES,MOTIVO DA CRITICIDADE,ADVOGADO DA PARTE CONTRÁRIA,DATA DE REABERTURA,DATA DE RECEBIMENTO,PARTE DESCRITA NA INICIAL,TIPO DE CONTINGÊNCIA,ANO DA BLACK FRIDAY,DATA DA ÚLTIMA MOVIMENTAÇÃO PROCESSUAL,OBSERVAÇÕES,OBSERVAÇÃO,TERCEIRO SOLVENTE,INCONTROVERSO (ZERAR PROVISÃO),RESULTADO,DATA DE SOLICITAÇÃO DE ENCERRAMENTO,DATA DE ENCERRAMENTO NO TRIBUNAL,MOTIVO DE ENCERRAMENTO,RECLAMAÇÃO ANTERIOR NO PROCON?,DATA DE REGISTRO DO ENCERRAMENTO,EXISTE PROCESSO COM O MESMO CPF?,CÍVEL MASSA - RESPONSABILIDADE,ESTRATÉGIA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,JUSTIFICATIVA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,CÍVEL MASSA - TIPOS DE TERCEIRO,PARTE CONTRÁRIA DATA ADMISSÃO,PARTE CONTRÁRIA DATA DISPENSA,PARTE CONTRÁRIA - STATUS EM FOLHA,PARTE CONTRÁRIA - MATRICULA,PARTE CONTRÁRIA - CARGO - CARGO (GRUPO),MOTIVO DA BAIXA PROVISÓRIA,PRODUTO,FABRICANTE DO PRODUTO,VALOR DO PRODUTO,PROCESSO - Nº. PEDIDO,DATA DO PEDIDO,LISTA LOJISTA - NOME,LISTA LOJISTA - ID,DATA DA COMPRA,TRANSPORTADORA,NÚMERO DA NOTA FISCAL,SITE DA COMPRA,DATA DO FATO GERADOR,DATA FATO GERADOR,DATA DO FATO GERADOR.1,DATA DO FATO GERADOR.2,INDIQUE A FILIAL,Data da Baixa Provisória,DATA DE REATIVAÇÃO - nativo,DATA DA REATIVAÇÃO -,E-MAIL - PARTE CONTRÁRIA,Processo - RESPONSÁVEL PELA VALIDAÇÃO - AUTOMÁTICO,Processo - RESPONSÁVEL PELA VALIDAÇÃO - MANUAL,PARA QUAL STATUS DESEJA ALTERAR?,MOTIVO DA ALTERAÇÃO DE STATUS,APTO PARA ACORDO?,ILEGITIMIDADE PASSIVA,PROJETO RECORTE MASSA?,Processo - EVENTO - CÍVEL,Processo - POSSUI A INICIAL?,Processo - CARTEIRA ESTRATÉGICO - CIVEL,Processo - MOTIVO DA APTIDÃO ?,PROCESSO - VIA NO POLO,PROCESSO - OBJETO CÍVEL (2) - NEW - SECUNDÁRIO,PROCESSO - OBJETO CÍVEL (2) - NEW - ASSUNTO,FEIRÃO LIMPA NOME,DESENROLA BRASIL,SUBSÍDIOS DISPONIBILIZADOS ATÉ O MOMENTO DE INSERÇÃO DA DEFESA?,APRESENTADA DEFESA GENÉRICA?,CATEGORIZAÇÃO BANQI,GRUPO CASAS BAHIA NO POLO DA AÇÃO?,Processo - DATA DA ABERTURA DE CONTA,PAGAR HONORÁRIOS AO ESCRITÓRIO?,Pedido,ADVOGADO OFENSOR (CÍV. MASSA),CÍVEL MASSA - FLUXO DE RESSARCIMENTO?,MATRIZ SEGURO,SEGUIR COM O PAGAMENTO DE HONORARIOS
0,298257,JEC.199637,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),VÍCIO DO PRODUTO,PRODUTO DE TERCEIROS,2015-11-23,BAIXA PROVISORIA,2112003054.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,28509.00,JUDICIAL,RJ,CAMPOS DOS GOYTACAZES,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,4ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2015-11-05,0041654-95.2015.8.19.0014,LUIZ CARLOS PESSANHA,473.509.467-91,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,CUMPRIMENTO DE SENTENÇA,DIRETA,GUILHERME SPAMER,2024-06-28 20:51:58.858,NaT,0,0.00,NÃO,YASMIN BARBOSA VICENTINI,RAFAEL EPISCOPO RODRIGUES COSTA,NaN,NÃO,TERCEIRO - ZURICH MINAS BRASIL SEGUROS S/A CONTINENTAL LTDA,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,2018-07-27 16:02:33.797,2019-08-07,NOVA CASA BAHIA S/A (CASAS BAHIA),PASSIVO,NaN,2017-04-26,NaN,PROCESSOS ENCERRADOS POR BANCO CONFORME ANALISE FEITA EM PLANILHA ENVIADA A GERENCIA DO PLANEJAM...,ZURICH,NaN,PARCIALMENTE PROCEDENTE,2018-08-24,2020-11-04,CONDENAÇÃO COM OBF E PAGAMENTO,NÃO,2020-11-04,NaN,SOLIDÁRIA,ACORDO,DECISÃO DESFAVORÁVEL,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,GELADEIRA,NI,0.00,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2024-06-28 20:51:58.858,NaN,NaT,NaN,NaN,NaN,2 - DE ENCERRADO PARA BAIXA PROVISÓRIA,CUSTAS REMANESCENTE,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NÃO SE APLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,620996,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),VÍCIO DO PRODUTO,PRODUTO DE TERCEIROS,2017-07-24,ATIVO,2112003054.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,15000.00,JUDICIAL,RJ,SÃO GONÇALO,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,8ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2017-07-05,0056557-34.2016.8.19.0004,IVONETE ALMEIDA ALVES,720.271.697-68,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,CONHECIMENTO,NaN,GABRIELLE F MALPELLI,NaT,NaT,3168,5069.59,NÃO,NAYARA CARLA DE SOUSA,LEONARDO PAULO LOMBARDI RODRIGUES - CNOVA,NaN,NÃO,NaN,NaN,EMERSON DE OLIVEIRA MARINS,NaT,2017-07-18,NaN,PASSIVO,NaN,NaT,NaN,NaN,ZURICH,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NÃO,SOLIDÁRIA,DEFESA,RESPONSABILIDADE DE TERCEIRO,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,COLCHÃO,CASTOR COLCHÕES,0.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,SEGURO,NÃO ATENDIMENTO AO CONSUMIDOR,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
2,565741,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),GARANTIA ESTENDIDA,NÃO ATENDIMENTO AO CONSUMIDOR -GE,2017-02-16,ATIVO,2106500768.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,15522.00,JUDICIAL,RJ,NITERÓI,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,9ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-03-29,0035236-46.2016.8.19.0002,ANDRE ESTABILA NOGUEIRA,012.882.487-50,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,CUMPRIMENTO DE SENTENÇA,DIRETA,JHONATAS.MELO,NaT,NaT,1854,2966.86,NÃO,YASMIN BARBOSA VICENTINI,RAFAEL EPISCOPO RODRIGUES COSTA,NaN,NÃO,"TERCEIRO - ZURICH MINAS BRASIL SEGUROS S.A, TERCEIRO - ALCATEL-LUCENT BRASIL S/A",NaN,MARCIA SOUZA - 186764,NaT,2017-02-07,NaN,PASSIVO,NaN,NaT,NaN,NaN,ZURICH,SIM,NaN,NaT,NaT,NaN,NaN,NaT,NÃO,SOLIDÁRIA,ACORDO,DECISÃO DESFAVORÁVEL,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,ESTRATÉGIA,SIM,NÃO SE APLICA,NÃO SE APLICA,NÃO,NÃO,NaN,NaN,NaN,SIM,NaN,NaN,"DANOS MATERIAIS, DANOS MATERIAIS, DANOS MORAIS, DANOS MORAIS",NaN,NaN,NaN,
3,641644,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),GARANTIA ESTENDIDA,NÃO ATENDIMENTO AO CONSUMIDOR -GE,2017-10-06,ATIVO,2106500768.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,7283.00,JUDICIAL,RJ,RIO DE JANEIRO - CAMPO GRANDE,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,1ª VARA CÍVEL,AÇÃO DE RESCISÃO CONTRATUAL,2017-09-11,00316694320178190205,VANDA CARLOTA FERREIRA,081.539.947-27,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,RECURSAL (TJ),DIRETA,YASMIN BARBOSA VICENTINI,NaT,NaT,1854,2966.86,NÃO,YASMIN BARBOSA VICENTINI,RAFAEL EPISCOPO RODRIGUES COSTA,NaN,NÃO,"TERCEIRO - BSH CONTINENTAL ELETRODOMÉSTICO LTDA, TERCEIRO - ZURICH MINAS BRASIL SEGURO S/A",NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,2017-10-04,NaN,PASSIVO,NaN,NaT,NaN,NaN,ZURICH,NaN,NaN,NaT,NaT,NaN,NÃO,NaT,NaN,SOLIDÁRIA,DEFESA,SUBSÍDIOS FAVORÁVEIS,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,NaN,NaN,NaN,ESTRATÉGIA,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM,NaN,
4,653245,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),GARANTIA ESTENDIDA,NÃO ATENDIMENTO AO CONSUMIDOR -GE,2017-11-21,ATIVO,2106500768.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,9370.00,JUDICIAL,RJ,RIO DE JANEIRO - SANTA CRUZ,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,2ª VARA CÍVEL,AÇÃO DE RESCISÃO CONTRATUAL,2017-08-09,00029184320178190206,KELEI DE FREITAS CORREIA,997.452.087-87,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,CONHECIMENTO,DIRETA,JOÃO PAULO TABAI DE JESUS,NaT,NaT,0,0.00,NÃO,YASMIN BARBOSA VICENTINI,RAFAEL EPISCOPO RODRIGUES COSTA,NaN,NÃO,"RÉU - INDUSTRIA DE MOVEIS BARTIRA LTDA , RÉU - ZURICH MINAS BRASIL SEGUROS S.A",NaN,DEFENSORIA PUBLICA DO ESTADO DO RIO DE JANEIRO,NaT,2017-09-22,NaN,PASSIVO,NaN,NaT,NaN,NaN,ZURICH,NaN,NaN,NaT,NaT,NaN,NÃO,NaT,NaN,TERCEIROS,DEFESA,SUBSÍDIOS FAVORÁVEIS,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,GUARDA ROUPA,BARTIRA,399.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,2015-11-27,NaN,NaN,NaN,NaN,2015-11-27,NaT,NaN,NaN,NaT,NaN,NaT,NaN,ROBERTA LUANA ROCHA,ROBERTA LUANA ROCHA,NaN,NaN,NÃO,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM,NaN,

In [0]:
cond_vazio = df_zurich['MATRIZ SEGURO'].isna() | (df_zurich['MATRIZ SEGURO'] == '')

# Verifica se está na lista de exclusão
cond_nao_pagar = df_zurich['MATRIZ SEGURO'].isin(nao_pagar)

# 2. Defina as listas de Condições e Escolhas (na mesma ordem)
condicoes = [
    cond_vazio,      # Prioridade 1: Se for vazio
    cond_nao_pagar   # Prioridade 2: Se estiver na lista 'nao_pagar'
]

escolhas = [
    'NÃO SE APLICA', # Resultado para vazio
    'NÃO'            # Resultado se estiver na lista
]

# 3. Aplica a lógica com np.select
# O argumento 'default' é o que acontece se NENHUMA condição acima for atendida (ou seja, não está na lista)
df_zurich['SEGUIR COM O PAGAMENTO DE HONORARIOS'] = np.select(condicoes, escolhas, default='SIM')

In [0]:
df_zurich.head(10)

,PROCESSO - ID,PASTA,GRUPO,ÁREA DO DIREITO,SUB-ÁREA DO DIREITO,ESTEIRA,ASSUNTO (CÍVEL) - PRINCIPAL,ASSUNTO (CÍVEL) - ASSUNTO,DATA REGISTRADO,STATUS,CENTRO DE CUSTO / ÁREA DEMANDANTE - CÓDIGO,EMPRESA,ADVOGADO RESPONSÁVEL,VALOR DA CAUSA,ESFERA,ESTADO,COMARCA,FORO/TRIBUNAL/ÓRGÃO,VARA/ÓRGÃO,AÇÃO,DISTRIBUIÇÃO,NÚMERO DO PROCESSO,PARTE CONTRÁRIA NOME,PARTE CONTRÁRIA CPF,ESCRITÓRIO EXTERNO,Escritório Anterior,FASE,COMPRA DIRETA OU MARKETPLACE? - NEW,USUÁRIO CADASTRANTE,DATA DA BAIXA PROVISÓRIA,DATA DA REATIVAÇÃO,VALOR PROVISIONADO,VALOR PROVISIONADO ATUALIZADO,PROCESSO CRITICO? (CÍVEL),ASSISTENTE JURÍDICO - CÍVEL,ASSISTENTE JURÍDICO -,DATA AUDIENCIA INICIAL,RECLAMAÇÃO BLACK FRIDAY?,OUTRAS PARTES / NÃO-CLIENTES,MOTIVO DA CRITICIDADE,ADVOGADO DA PARTE CONTRÁRIA,DATA DE REABERTURA,DATA DE RECEBIMENTO,PARTE DESCRITA NA INICIAL,TIPO DE CONTINGÊNCIA,ANO DA BLACK FRIDAY,DATA DA ÚLTIMA MOVIMENTAÇÃO PROCESSUAL,OBSERVAÇÕES,OBSERVAÇÃO,TERCEIRO SOLVENTE,INCONTROVERSO (ZERAR PROVISÃO),RESULTADO,DATA DE SOLICITAÇÃO DE ENCERRAMENTO,DATA DE ENCERRAMENTO NO TRIBUNAL,MOTIVO DE ENCERRAMENTO,RECLAMAÇÃO ANTERIOR NO PROCON?,DATA DE REGISTRO DO ENCERRAMENTO,EXISTE PROCESSO COM O MESMO CPF?,CÍVEL MASSA - RESPONSABILIDADE,ESTRATÉGIA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,JUSTIFICATIVA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,CÍVEL MASSA - TIPOS DE TERCEIRO,PARTE CONTRÁRIA DATA ADMISSÃO,PARTE CONTRÁRIA DATA DISPENSA,PARTE CONTRÁRIA - STATUS EM FOLHA,PARTE CONTRÁRIA - MATRICULA,PARTE CONTRÁRIA - CARGO - CARGO (GRUPO),MOTIVO DA BAIXA PROVISÓRIA,PRODUTO,FABRICANTE DO PRODUTO,VALOR DO PRODUTO,PROCESSO - Nº. PEDIDO,DATA DO PEDIDO,LISTA LOJISTA - NOME,LISTA LOJISTA - ID,DATA DA COMPRA,TRANSPORTADORA,NÚMERO DA NOTA FISCAL,SITE DA COMPRA,DATA DO FATO GERADOR,DATA FATO GERADOR,DATA DO FATO GERADOR.1,DATA DO FATO GERADOR.2,INDIQUE A FILIAL,Data da Baixa Provisória,DATA DE REATIVAÇÃO - nativo,DATA DA REATIVAÇÃO -,E-MAIL - PARTE CONTRÁRIA,Processo - RESPONSÁVEL PELA VALIDAÇÃO - AUTOMÁTICO,Processo - RESPONSÁVEL PELA VALIDAÇÃO - MANUAL,PARA QUAL STATUS DESEJA ALTERAR?,MOTIVO DA ALTERAÇÃO DE STATUS,APTO PARA ACORDO?,ILEGITIMIDADE PASSIVA,PROJETO RECORTE MASSA?,Processo - EVENTO - CÍVEL,Processo - POSSUI A INICIAL?,Processo - CARTEIRA ESTRATÉGICO - CIVEL,Processo - MOTIVO DA APTIDÃO ?,PROCESSO - VIA NO POLO,PROCESSO - OBJETO CÍVEL (2) - NEW - SECUNDÁRIO,PROCESSO - OBJETO CÍVEL (2) - NEW - ASSUNTO,FEIRÃO LIMPA NOME,DESENROLA BRASIL,SUBSÍDIOS DISPONIBILIZADOS ATÉ O MOMENTO DE INSERÇÃO DA DEFESA?,APRESENTADA DEFESA GENÉRICA?,CATEGORIZAÇÃO BANQI,GRUPO CASAS BAHIA NO POLO DA AÇÃO?,Processo - DATA DA ABERTURA DE CONTA,PAGAR HONORÁRIOS AO ESCRITÓRIO?,Pedido,ADVOGADO OFENSOR (CÍV. MASSA),CÍVEL MASSA - FLUXO DE RESSARCIMENTO?,MATRIZ SEGURO,SEGUIR COM O PAGAMENTO DE HONORARIOS
0,298257,JEC.199637,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),VÍCIO DO PRODUTO,PRODUTO DE TERCEIROS,2015-11-23,BAIXA PROVISORIA,2112003054.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,28509.00,JUDICIAL,RJ,CAMPOS DOS GOYTACAZES,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,4ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2015-11-05,0041654-95.2015.8.19.0014,LUIZ CARLOS PESSANHA,473.509.467-91,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,CUMPRIMENTO DE SENTENÇA,DIRETA,GUILHERME SPAMER,2024-06-28 20:51:58.858,NaT,0,0.00,NÃO,YASMIN BARBOSA VICENTINI,RAFAEL EPISCOPO RODRIGUES COSTA,NaN,NÃO,TERCEIRO - ZURICH MINAS BRASIL SEGUROS S/A CONTINENTAL LTDA,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,2018-07-27 16:02:33.797,2019-08-07,NOVA CASA BAHIA S/A (CASAS BAHIA),PASSIVO,NaN,2017-04-26,NaN,PROCESSOS ENCERRADOS POR BANCO CONFORME ANALISE FEITA EM PLANILHA ENVIADA A GERENCIA DO PLANEJAM...,ZURICH,NaN,PARCIALMENTE PROCEDENTE,2018-08-24,2020-11-04,CONDENAÇÃO COM OBF E PAGAMENTO,NÃO,2020-11-04,NaN,SOLIDÁRIA,ACORDO,DECISÃO DESFAVORÁVEL,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,GELADEIRA,NI,0.00,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2024-06-28 20:51:58.858,NaN,NaT,NaN,NaN,NaN,2 - DE ENCERRADO PARA BAIXA PROVISÓRIA,CUSTAS REMANESCENTE,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NÃO SE APLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA
1,620996,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),VÍCIO DO PRODUTO,PRODUTO DE TERCEIROS,2017-07-24,ATIVO,2112003054.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,15000.00,JUDICIAL,RJ,SÃO GONÇALO,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,8ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2017-07-05,0056557-34.2016.8.19.0004,IVONETE ALMEIDA ALVES,720.271.697-68,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,CONHECIMENTO,NaN,GABRIELLE F MALPELLI,NaT,NaT,3168,5069.59,NÃO,NAYARA CARLA DE SOUSA,LEONARDO PAULO LOMBARDI RODRIGUES - CNOVA,NaN,NÃO,NaN,NaN,EMERSON DE OLIVEIRA MARINS,NaT,2017-07-18,NaN,PASSIVO,NaN,NaT,NaN,NaN,ZURICH,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NÃO,SOLIDÁRIA,DEFESA,RESPONSABILIDADE DE TERCEIRO,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,COLCHÃO,CASTOR COLCHÕES,0.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,SEGURO,NÃO ATENDIMENTO AO CONSUMIDOR,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA
2,565741,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),GARANTIA ESTENDIDA,NÃO ATENDIMENTO AO CONSUMIDOR -GE,2017-02-16,ATIVO,2106500768.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,15522.00,JUDICIAL,RJ,NITERÓI,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,9ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-03-29,0035236-46.2016.8.19.0002,ANDRE ESTABILA NOGUEIRA,012.882.487-50,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,CUMPRIMENTO DE SENTENÇA,DIRETA,JHONATAS.MELO,NaT,NaT,1854,2966.86,NÃO,YASMIN BARBOSA VICENTINI,RAFAEL EPISCOPO RODRIGUES COSTA,NaN,NÃO,"TERCEIRO - ZURICH MINAS BRASIL SEGUROS S.A, TERCEIRO - ALCATEL-LUCENT BRASIL S/A",NaN,MARCIA SOUZA - 186764,NaT,2017-02-07,NaN,PASSIVO,NaN,NaT,NaN,NaN,ZURICH,SIM,NaN,NaT,NaT,NaN,NaN,NaT,NÃO,SOLIDÁRIA,ACORDO,DECISÃO DESFAVORÁVEL,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,ESTRATÉGIA,SIM,NÃO SE APLICA,NÃO SE APLICA,NÃO,NÃO,NaN,NaN,NaN,SIM,NaN,NaN,"DANOS MATERIAIS, DANOS MATERIAIS, DANOS MORAIS, DANOS MORAIS",NaN,NaN,NaN,NÃO SE APLICA
3,641644,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),GARANTIA ESTENDIDA,NÃO ATENDIMENTO AO CONSUMIDOR -GE,2017-10-06,ATIVO,2106500768.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,7283.00,JUDICIAL,RJ,RIO DE JANEIRO - CAMPO GRANDE,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,1ª VARA CÍVEL,AÇÃO DE RESCISÃO CONTRATUAL,2017-09-11,00316694320178190205,VANDA CARLOTA FERREIRA,081.539.947-27,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,RECURSAL (TJ),DIRETA,YASMIN BARBOSA VICENTINI,NaT,NaT,1854,2966.86,NÃO,YASMIN BARBOSA VICENTINI,RAFAEL EPISCOPO RODRIGUES COSTA,NaN,NÃO,"TERCEIRO - BSH CONTINENTAL ELETRODOMÉSTICO LTDA, TERCEIRO - ZURICH MINAS BRASIL SEGURO S/A",NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,2017-10-04,NaN,PASSIVO,NaN,NaT,NaN,NaN,ZURICH,NaN,NaN,NaT,NaT,NaN,NÃO,NaT,NaN,SOLIDÁRIA,DEFESA,SUBSÍDIOS FAVORÁVEIS,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,NaN,NaN,NaN,ESTRATÉGIA,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM,NaN,NÃO SE APLICA
4,653245,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),GARANTIA ESTENDIDA,NÃO ATENDIMENTO AO CONSUMIDOR -GE,2017-11-21,ATIVO,2106500768.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,9370.00,JUDICIAL,RJ,RIO DE JANEIRO - SANTA CRUZ,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,2ª VARA CÍVEL,AÇÃO DE RESCISÃO CONTRATUAL,2017-08-09,00029184320178190206,KELEI DE FREITAS CORREIA,997.452.087-87,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,CONHECIMENTO,DIRETA,JOÃO PAULO TABAI DE JESUS,NaT,NaT,0,0.00,NÃO,YASMIN BARBOSA VICENTINI,RAFAEL EPISCOPO RODRIGUES COSTA,NaN,NÃO,"RÉU - INDUSTRIA DE MOVEIS BARTIRA LTDA , RÉU - ZURICH MINAS BRASIL SEGUROS S.A",NaN,DEFENSORIA PUBLICA DO ESTADO DO RIO DE JANEIRO,NaT,2017-09-22,NaN,PASSIVO,NaN,NaT,NaN,NaN,ZURICH,NaN,NaN,NaT,NaT,NaN,NÃO,NaT,NaN,TERCEIROS,DEFESA,SUBSÍDIOS FAVORÁVEIS,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,GUARDA ROUPA,BARTIRA,399.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,2015-11-27,NaN,NaN,NaN,NaN,2015-11-27,NaT,NaN,NaN,NaT,NaN,NaT,NaN,ROBERTA LUANA ROCHA,ROBERTA LUANA ROCHA,NaN,NaN,NÃO,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM,NaN,NÃO SE APLICA
5,799770,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,NaN,VÍCIO DO PRODUTO,PRODUTO DE TERCEIROS,2019-07-12,ATIVO,2106501056.00,CASAS BAHIA ONLINE,INGRID VASQUES DE LACERDA,39936.20,JUDICIAL,RJ,RIO DE JANEIRO - CAMPO GRANDE,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,3ª VARA CÍVEL,AÇÃO DE OBRIGAÇÃO DE FAZER,2019-07-10,0022995-08.2019.8.19.0205,VALTEIR DE SOUZA,632.231.637-00,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,RECURSAL (TJ),DIRETA,GABRIELA GARCIA,NaT,NaT,3168,5069.59,NÃO,ANNA KAROLYNE GOMES DE OLIVEIRA ABADE,NaN,NaN,NÃO,"REQUERIDO - ZURICH MINAS BRASIL SEGUROS SA, REQUERIDO - AMERICANFLEX INDUSTRIAS REUNIDAS LTDA",NaN,EDIVALDO DE SOUZA,NaT,2019-07-12,CASAS BAHIA,PASSIVO,NaN,NaT,NaN,NaN,ZURICH,NaN,NaN,NaT,NaT,NaN,NÃO,NaT,SIM,SOLIDÁRIA,ACORDO,AUDITORIA,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,CAMA,AMERICANFLEX,2599.00,NaN,2018-07-31,NÃO SE APLICA,NÃO SE APLICA,2018-07-31,NaN,NaN,NaN,NaN,2018-07-31,NaT,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,SIM,NaN,NaN,NaN,NaN,NaN,NaN,SIM,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,SIM,NaN,NaN,"DANOS MATERIAIS, DANOS MORAIS",NaN,NaN,NaN,NÃO SE APLICA
6,709796,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,NaN,VÍCIO DO PRODUTO,PRODUTO DE TERCEIROS,2018-06-11,REATIVADO,2112003054.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,30209.00,JUDICIAL,RJ,MAGÉ,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2017-12-07,0011676-16.2017.8.19.0075,DILZA FAUSTINO NUNES DA SILVA,827.864.027-00,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",FERREIRA LEÃO ADVOGADOS - (CÍVEL),RECURSAL (TJ),DIRETA,LARYSSA GALINDO,NaT,NaT,3168,5069.59,NÃO,ANNA KAROLYNE GOMES DE OLIVEIRA ABADE,NaN,NaN,NÃO,RÉU - ZURICH MINAS BRASIL SEGUROS SA,NaN,073027 - JOSE MARCOS MOTTA RAMOS,NaT,2018-06-11,"VIA VAREJO S/A,",PASSIVO,NaN,NaT,NaN,NaN,ZURICH,SIM,AÇÃO PROCEDENTE,NaT,2023-06-14,AÇÃO PROCEDENTE,NÃO,2023-06-14,NaN,CASAS BAHIA,DEFESA,SUBSÍDIOS FAVORÁVEIS,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NaN,2024-12-19 15:19:42.298,NaN,NaN,NaN,4 - DE ENCERRADO PARA REATIVADO,4.1 - OBF,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NÃO SE APLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DANOS MORAIS,NaN,NaN,NaN,NÃO SE APLICA
7,772338,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,NaN,SEGURO,COBERTURA DO SEGURO,2019-03-26,ATIVO,2106500768.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,20000.00,JUDICIAL,RJ,NOVA IGUAÇÚ,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,5ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2019-03-13,0016933-65.2019.8.19.0038,SERGIO ANTONIO DE ALMEIDA,701.749.207-25,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,CONHECIMENTO,DIRETA,MARIANA TOMAZ MAZUR,NaT,NaT,1212,1939.50,NÃO,ANNA KAROLYNE GOMES DE OLIVEIRA ABADE,NaN,NaN,NÃO,"REQUERIDO - ZURICH MINAS BRASIL SEGUROS SA, REQUERIDO - LINKCELL CELULARES",NaN,CLETO SILVA MARTINS OAB/RJ 159.473,NaT,2019-03-26,VIA VAREJO S/A,PASSIVO,NaN,NaT,NaN,NaN,ZURICH,NaN,NaN,NaT,NaT,NaN,NÃO,NaT,NÃO,SOLIDÁRIA,DEFESA,RESPONSABILIDADE DE TERCEIRO,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,CELULAR,SAMSUNG,0.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,NaT,NaN,NaN,NaN,NaN,2018-12-27,NaT,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,ESTRATÉGIA,SIM,NÃO SE APLICA,NÃO SE APLICA,NÃO,NÃO,NaN,NaN,NaN,SIM,NaN,NaN,"DANOS MORAIS, HONORÁRIOS",NaN,NaN,NaN,NÃO SE APLICA
8,803356,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,JEC,NaN,VÍCIO DO PRODUTO,PRODUTO DE TERCEIROS,2019-07-29,REATIVADO,2112003054.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,39665.28,JUDICIAL,RJ,RIO DE JANEIRO - CAMPO GRANDE,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,26º JEC,AÇÃO DE OBRIGAÇÃO DE FAZER,2019-07-27,0025324-90.2019.8.19.0205,VALTEIR DE SOUZA,632.231.637-00,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",SIQUEIRA CASTRO ADVOGADOS (CÍVEL),EXECUÇÃO,DIRETA,DENISE MACEDO,2023-07-03 15:12:01.133,NaT,3168,5069.59,NÃO,ANNA KAROLYNE GOMES DE OLIVEIRA ABADE,NaN,2019-10-15 15:00:00,NÃO,"RÉU - ELECTROLUX DO BRASIL S/A , RÉU - ZURICH MINAS BRASIL SEGUROS SA, RÉU - CDF CENTRAL DE FUN...",NaN,EDIVALDO DE SOUZA - 111867 RJ,2023-03-10 16:06:43.029,2019-07-29,CASAS BAHIA,PASSIVO,NaN,NaT,NaN,NaN,ZURICH,NaN,AÇÃO PROCEDENTE EM PARTE,NaT,2023-08-29,AÇÃO PROCEDENTE EM PARTE,NÃO,2023-08-29,NaN,CASAS BAHIA,ACORDO,DECISÃO DESFAVORÁVEL,SERVIÇO,NaT,NaT,NaN,NaN,NaN,PAGAMENTO,FOGÃO,ELECTROLUX,1839.00,NaN,2019-06-21,NÃO SE APLICA,NÃO SE APLICA,2019-06-21,NaN,NaN,NaN,NaN,2019-06-21,NaT,NaN,NaN,2023-07-03 15:12:01.133,NaN,2024-10-08 18:14:35.485,NaN,KEVIN ALEX CUSTODIO DA SILVA,KEVIN ALEX CUSTODIO DA SILVA,4 - DE ENCERRADO PARA REATIVADO,4.1 - PAGAMENTO,NÃO,NaN,NaN,NaN,NaN,NaN,ESTRATÉGIA,NaN,DESCUMPRIMENTO DE OFERTA,DESCUMPRIMENTO DE OFERTA - DO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DANOS MATERIAIS, DANOS MORAIS, HONORÁRIOS, OBRIGAÇÃO DE FAZER OU NÃO FAZER",NaN,NaN,NaN,NÃO SE APLICA
9,700982,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,NaN,ENTREGA E MONTAGEM,ENTREGA COM AVARIA - EM,2018-04-26,REATIVADO,2114013052.00,GRUPO CASAS BAHIA S/A,INGRID VASQUES DE LACERDA,6374.43,JUDICIAL,RJ,CAMPOS DOS GOYTACAZES,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,3ª VARA CÍVEL,AÇÃO DE RESTITUIÇÃO,2018-04-25,0011543-26.2018.8.19.0014,EDSON COSTA DE SOUSA,092.894.207-40,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",NaN,RECURSAL (TJ),DIRETA,VICTOR DIAS CHANG,NaT,NaT,3913,6261.78,NÃO,YASMIN BARBOSA VICENTINI,NaN,NaN,NÃO,"RÉU - MOTOROLA DO BRASIL LTDA, RÉU - ZURICH MINAS BRASIL SEGUROS SA",NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,2018-04-26,VIA VAREJO S/A,PASSIVO,NaN,NaT,NaN,NaN,ZURICH,NaN,IMPROCEDÊNCIA,NaT,2023-10-27,IMPROCEDÊNCIA,NÃO,2023-10-27,NaN,SOLIDÁRIA,DEFESA,RESPONSABILIDADE DE TERCEIRO,SEGURO,NaT,NaT,NaN,NaN,NaN,NaN,CELULAR,MOTOROLA,1198.43,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,2017-07-26,NaN,NaN,NaN,NaN,2017-07-26,NaT,NaN,NaN,NaT,NaN,2024-08-21 16:36:52.799,NaN,NaN,NaN,4 - DE ENCERRADO PARA REATIVADO,4.1 - RECURSO,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NÃO SE APLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DANOS MORAIS,NaN,NaN,NaN,NÃO SE APLICA

In [0]:
df_zurich.shape

(1310, 115)

In [0]:
df_ger = df_ger.merge(
    df_zurich[['PROCESSO - ID', 'SEGUIR COM O PAGAMENTO DE HONORARIOS']],
    on='PROCESSO - ID', 
    how='left'
)

In [0]:
conds = df_ger['SEGUIR COM O PAGAMENTO DE HONORARIOS'].isnull()

# Leia-se: "No df_ger, onde a condição é True, na coluna 'SEGUIR...', receba 'NÃO SE APLICA'"
df_ger.loc[conds, 'SEGUIR COM O PAGAMENTO DE HONORARIOS'] = 'NÃO SE APLICA'

In [0]:
df_ger.head()

,PROCESSO - ID,PASTA,GRUPO,ÁREA DO DIREITO,SUB-ÁREA DO DIREITO,ESTEIRA,ASSUNTO (CÍVEL) - PRINCIPAL,ASSUNTO (CÍVEL) - ASSUNTO,DATA REGISTRADO,STATUS,CENTRO DE CUSTO / ÁREA DEMANDANTE - CÓDIGO,EMPRESA,ADVOGADO RESPONSÁVEL,VALOR DA CAUSA,ESFERA,ESTADO,COMARCA,FORO/TRIBUNAL/ÓRGÃO,VARA/ÓRGÃO,AÇÃO,DISTRIBUIÇÃO,NÚMERO DO PROCESSO,PARTE CONTRÁRIA NOME,PARTE CONTRÁRIA CPF,ESCRITÓRIO EXTERNO,Escritório Anterior,FASE,COMPRA DIRETA OU MARKETPLACE? - NEW,USUÁRIO CADASTRANTE,DATA DA BAIXA PROVISÓRIA,DATA DA REATIVAÇÃO,VALOR PROVISIONADO,VALOR PROVISIONADO ATUALIZADO,PROCESSO CRITICO? (CÍVEL),ASSISTENTE JURÍDICO - CÍVEL,ASSISTENTE JURÍDICO -,DATA AUDIENCIA INICIAL,RECLAMAÇÃO BLACK FRIDAY?,OUTRAS PARTES / NÃO-CLIENTES,MOTIVO DA CRITICIDADE,ADVOGADO DA PARTE CONTRÁRIA,DATA DE REABERTURA,DATA DE RECEBIMENTO,PARTE DESCRITA NA INICIAL,TIPO DE CONTINGÊNCIA,ANO DA BLACK FRIDAY,DATA DA ÚLTIMA MOVIMENTAÇÃO PROCESSUAL,OBSERVAÇÕES,OBSERVAÇÃO,TERCEIRO SOLVENTE,INCONTROVERSO (ZERAR PROVISÃO),RESULTADO,DATA DE SOLICITAÇÃO DE ENCERRAMENTO,DATA DE ENCERRAMENTO NO TRIBUNAL,MOTIVO DE ENCERRAMENTO,RECLAMAÇÃO ANTERIOR NO PROCON?,DATA DE REGISTRO DO ENCERRAMENTO,EXISTE PROCESSO COM O MESMO CPF?,CÍVEL MASSA - RESPONSABILIDADE,ESTRATÉGIA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,JUSTIFICATIVA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,CÍVEL MASSA - TIPOS DE TERCEIRO,PARTE CONTRÁRIA DATA ADMISSÃO,PARTE CONTRÁRIA DATA DISPENSA,PARTE CONTRÁRIA - STATUS EM FOLHA,PARTE CONTRÁRIA - MATRICULA,PARTE CONTRÁRIA - CARGO - CARGO (GRUPO),MOTIVO DA BAIXA PROVISÓRIA,PRODUTO,FABRICANTE DO PRODUTO,VALOR DO PRODUTO,PROCESSO - Nº. PEDIDO,DATA DO PEDIDO,LISTA LOJISTA - NOME,LISTA LOJISTA - ID,DATA DA COMPRA,TRANSPORTADORA,NÚMERO DA NOTA FISCAL,SITE DA COMPRA,DATA DO FATO GERADOR,DATA FATO GERADOR,DATA DO FATO GERADOR.1,DATA DO FATO GERADOR.2,INDIQUE A FILIAL,Data da Baixa Provisória,DATA DE REATIVAÇÃO - nativo,DATA DA REATIVAÇÃO -,E-MAIL - PARTE CONTRÁRIA,Processo - RESPONSÁVEL PELA VALIDAÇÃO - AUTOMÁTICO,Processo - RESPONSÁVEL PELA VALIDAÇÃO - MANUAL,PARA QUAL STATUS DESEJA ALTERAR?,MOTIVO DA ALTERAÇÃO DE STATUS,APTO PARA ACORDO?,ILEGITIMIDADE PASSIVA,PROJETO RECORTE MASSA?,Processo - EVENTO - CÍVEL,Processo - POSSUI A INICIAL?,Processo - CARTEIRA ESTRATÉGICO - CIVEL,Processo - MOTIVO DA APTIDÃO ?,PROCESSO - VIA NO POLO,PROCESSO - OBJETO CÍVEL (2) - NEW - SECUNDÁRIO,PROCESSO - OBJETO CÍVEL (2) - NEW - ASSUNTO,FEIRÃO LIMPA NOME,DESENROLA BRASIL,SUBSÍDIOS DISPONIBILIZADOS ATÉ O MOMENTO DE INSERÇÃO DA DEFESA?,APRESENTADA DEFESA GENÉRICA?,CATEGORIZAÇÃO BANQI,GRUPO CASAS BAHIA NO POLO DA AÇÃO?,Processo - DATA DA ABERTURA DE CONTA,PAGAR HONORÁRIOS AO ESCRITÓRIO?,Pedido,ADVOGADO OFENSOR (CÍV. MASSA),CÍVEL MASSA - FLUXO DE RESSARCIMENTO?,SEGUIR COM O PAGAMENTO DE HONORARIOS
0,289797,CIV.23267,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),ENTREGA E MONTAGEM,ENTREGA DE PRODUTO DIVERSO - EM,2016-06-07,BAIXA PROVISORIA,2114013051.00,GRUPO CASAS BAHIA S/A,FELIPPE SILVA FOGAZZA,21720.00,JUDICIAL,RJ,NOVA IGUAÇÚ,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,7ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-05-14,'00505448220148190038,KEROLLYN DE OLIVEIRA VIRLA,N/I,LAURO RABHA,NaN,CUMPRIMENTO DE SENTENÇA,NaN,GUILHERME SPAMER,2024-07-08 14:49:15.126,NaT,0,0.00,NÃO,NAYARA CARLA DE SOUSA,LEONARDO PAULO LOMBARDI RODRIGUES - CNOVA,NaN,NaN,ADVOGADO ADVERSO - TATIANA BASTOS DE MELLO,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,NaT,NaN,PASSIVO,NaN,NaT,NaN,PROCESSOS ENCERRADOS POR BANCO CONFORME ANALISE FEITA EM PLANILHA ENVIADA A GERENCIA DO PLANEJAM...,NaN,NaN,PARCIALMENTE PROCEDENTE,2019-04-12 00:00:00,2020-11-04,CONDENAÇÃO COM OBF E PAGAMENTO,NaN,2020-11-04,NaN,NaN,ACORDO,DECISÃO DESFAVORÁVEL,LEGADO,NaT,NaT,NaN,NaN,NaN,NaN,ARMÁRIO MULTIUSO,BARTIRA,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2024-07-08 14:49:15.126,NaN,NaT,NaN,NaN,NaN,2 - DE ENCERRADO PARA BAIXA PROVISÓRIA,CUSTAS REMANESCENTE,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA
1,317446,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,JEC,MASSA (CÍVEL),VENDA DE CARTEIRA DE CRÉDITO,VENDA DE CARTEIRA DE CRÉDITO - VCC,2016-10-13,BAIXA PROVISORIA,2106503025.00,GLOBEX UTILIDADES S/A (GPA),FELIPPE SILVA FOGAZZA,40000.00,JUDICIAL,RJ,RIO DE JANEIRO,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,20ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-09-16,00176673020158190208,MARCELO PASCHOAL DE OLIVEIRA,068.477.487-96,LAURO RABHA,QUEIROZ E LAUTENSCHLAGER (CÍVEL),RECURSAL,NÃO SE APLICA,YNAIA OLIVEIRA DA SILVA - CNOVA,2021-06-28 00:00:00.000,NaT,0,0.00,NÃO,NAYARA CARLA DE SOUSA,LEONARDO PAULO LOMBARDI RODRIGUES - CNOVA,2016-10-18 14:20:00,NÃO,NaN,NaN,RENATO FRANCISCO DA SILVA NETO,2018-08-29 20:06:09.910,2016-10-03,NaN,PASSIVO,NaN,NaT,NaN,NaN,NÃO SE APLICA,NaN,NaN,2019-10-04 14:46:39,NaT,NaN,NÃO,NaT,NaN,NaN,ACORDO,DECISÃO DESFAVORÁVEL,VENDA DE CARTEIRA DE CRÉDITO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,NaT,NaN,NaN,NaN,NaN,NaT,1998-10-25,NaN,NaN,2021-06-28 00:00:00.000,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DANOS MORAIS,NaN,NaN,NÃO SE APLICA
2,290822,CIV.24393,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),VÍCIO DO PRODUTO,PRODUTO DE TERCEIROS,2016-08-29,REATIVADO,2112003054.00,GRUPO CASAS BAHIA S/A,ROBERTA LUANA ROCHA,116694.50,JUDICIAL,BA,JUAZEIRO,TRIBUNAL DE JUSTIÇA DO ESTADO DA BAHIA,2ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-08-15,'09618686420158050146,MARIA SANDRA LIMA SILVA,N/I,QUEIROZ CAVALCANTI ADVOGADOS,NaN,CONHECIMENTO,NaN,GUILHERME SPAMER,2024-04-09 16:45:28.054,NaT,3168,5069.59,NÃO,GABRIEL GALDINO DE OLIVEIRA,MARIANA LAMEIRA E SILVA,NaN,NaN,NaN,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,NaT,NaN,PASSIVO,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NaN,CASAS BAHIA,ACORDO,AUSÊNCIA DE SUBSÍDIOS,FORNECEDOR,NaT,NaT,NaN,NaN,NaN,PAGAMENTO,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2024-04-09 16:45:28.054,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,ESTRATÉGIA,NaN,NaN,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA
3,84996,JEC.217184GPA,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,JEC,MASSA (CÍVEL),ENTREGA E MONTAGEM,AUSÊNCIA DE ENTREGA - EM,2016-06-09,REATIVADO,2117920206.00,CASAS BAHIA ONLINE,ROBERTA LUANA ROCHA,807.04,JUDICIAL,AL,IGREJA NOVA,TRIBUNAL DE JUSTIÇA DO ESTADO DE ALAGOAS,JEC,AÇÃO DE INDENIZAÇÃO,2016-02-18,0700251-79.2015.8.02.0014,JOE JANIO DE OLIVEIRA DAVINO,055.833.364-80,QUEIROZ CAVALCANTI ADVOGADOS,NaN,EXECUÇÃO,MARKETPLACE,GUILHERME SPAMER,2018-05-23 00:00:00.000,NaT,3913,6261.78,NÃO,GABRIEL GALDINO DE OLIVEIRA,MARIANA LAMEIRA E SILVA,NaN,NÃO,NaN,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,2024-04-23,NaN,PASSIVO,NaN,NaT,NaN,NaN,NÃO SE APLICA,NaN,AUSÊNCIA DO AUTOR,NaT,2018-05-23,AUSÊNCIA DO AUTOR,NaN,NaT,NÃO,NaN,ACORDO,AUSÊNCIA DE SUBSÍDIOS,NÃO É TERCEIRO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2018-05-23 00:00:00.000,NaN,2024-04-15 18:19:25.459,NaN,NaN,NaN,4 - DE ENCERRADO PARA REATIVADO,4.1 - EXECUÇÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,SIM,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA
4,305154,JEC.222054,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),CRÉDITO E COBRANÇA,CARTÃO PF - COBRANÇA INDEVIDA COM NEGATIVAÇÃO,2016-05-31,REATIVADO,2106500311.00,GRUPO CASAS BAHIA S/A,JENIFFER CONCEICAO DE SOUZA,3006.80,JUDICIAL,SC,JOINVILLE,TRIBUNAL DE JUSTIÇA DO ESTADO DE SANTA CATARINA,2ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2015-09-08,0017211-67.2015.8.24.0038,VERA LUCIA CALVO,491.659.179-87,PINTO & SOARES ADVOGADOS ASSOCIADOS,NaN,CONHECIMENTO,DIRETA,GUILHERME SPAMER,NaT,NaT,0,0.00,NÃO,RAFAEL EPISCOPO RODRIGUES COSTA,WEVERTON SOUZA MATOS,NaN,NÃO,TERCEIRO - BANCO ITAUCRED,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,2019-10-23,VIA VAREJO,PASSIVO,NaN,NaT,NaN,NaN,ITAÚ,NaN,SANEAMENTO - MENDES E BARRETO,NaT,2025-06-27,SANEAMENTO - MENDES E BARRETO,NÃO,NaT,NaN,TERCEIROS,ACORDO,DECISÃO DESFAVORÁVEL,CARTÃO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,NaT,NaN,NaN,NaN,NaN,NaT,2015-09-08,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,SIM,NÃO,NaN,NaN,NaN,NaN,ESTRATÉGIA,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM,NÃO SE APLICA

In [0]:
df_fatu_hist_spark = spark.read.table("databox.juridico_comum.br_Consolidado_Honorarios")
df_fatu_hist = df_fatu_hist_spark.toPandas()

df_fatu_hist.head()

,mes_ano,processo_id,sub_area_direito,assunto_civel_principal,data_registro,data_confirmacao,status,centro_de_custo,empresa,acao,numero_do_processo,escritorio_externo,fase,data_de_registro_do_encerramento,motivo_de_encerramento,temos_improced_ncia,temos_acordo,qtd_parcela_mensalidade,b_nus_acordo,b_nus_improced_ncia,mensalidade_5_parcelas,mensalidade_jec_10m,mensalidade_vara_comum_18m,glosa,motivo_da_glosa,valor_total_a_pagar,consideracoes_escritorio,valor_pleiteado_escritorio,consideracoes_via_varejo,tipo,migracoes,chave_id_mes_pagto,chave_id_acordo,chave_id_improcedencia,chave_id_status
0,2025-01-01,124958,VARA COMUM,ENTREGA E MONTAGEM,2014-10-01,2024-12-14 00:00:00,BAIXA PROVISORIA,2116400206,CASAS BAHIA ONLINE,AÇÃO DE OBRIGAÇÃO DE FAZER,0000343-20.2014.8.08.0062,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",EXECUÇÃO,NaT,None,NENHUM,NENHUM,2.00,0,0,0.00,0,35,0.00,0,35.00,None,None,None,FATURAMENTO,None,12495845658,124958NENHUM,124958NENHUM,"124958BAIXA PROVISORIACHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)"
1,2025-01-01,259130,JEC,ENTREGA E MONTAGEM,2016-09-02,2024-12-14 00:00:00,REATIVADO,2116400206,CASAS BAHIA ONLINE,AÇÃO DE INDENIZAÇÃO,00014336720168080038,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",EXECUÇÃO,NaT,None,NENHUM,NENHUM,2.00,0,0,0.00,35,0,0.00,0,35.00,None,None,None,FATURAMENTO,None,25913045658,259130NENHUM,259130NENHUM,"259130REATIVADOCHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)"
2,2025-01-01,283753,VARA COMUM,ENTREGA E MONTAGEM,2012-08-17,2024-12-14 00:00:00,BAIXA PROVISORIA,2114013051,GRUPO CASAS BAHIA S/A,AÇÃO DE INDENIZAÇÃO,'00293971920128080024,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",CONHECIMENTO,NaT,None,NENHUM,NENHUM,2.00,0,0,0.00,0,35,0.00,0,35.00,None,None,None,FATURAMENTO,None,28375345658,283753NENHUM,283753NENHUM,"283753BAIXA PROVISORIACHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)"
3,2025-01-01,192717,JEC,DESCUMPRIMENTO CONTRATUAL,2016-02-23,2024-12-14 00:00:00,BAIXA PROVISORIA,2106501056,CASAS BAHIA ONLINE,AÇÃO DE INDENIZAÇÃO,0011044-87.2016.8.08.0347,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",EXECUÇÃO,NaT,None,NENHUM,NENHUM,2.00,0,0,0.00,35,0,0.00,0,35.00,None,None,None,FATURAMENTO,None,19271745658,192717NENHUM,192717NENHUM,"192717BAIXA PROVISORIACHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)"
4,2025-01-01,99574,JEC,VENDA DE CARTEIRA DE CRÉDITO (CHEQUES),2016-07-01,2024-12-30 00:00:00,REATIVADO,2106503025,GLOBEX UTILIDADES S/A (GPA),AÇÃO DE INDENIZAÇÃO,'00079999020158080030,"CHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)",RECURSAL,NaT,None,NENHUM,NENHUM,2.00,0,0,0.00,35,0,0.00,0,35.00,None,None,None,FATURAMENTO,None,9957445658,99574NENHUM,99574NENHUM,"99574REATIVADOCHALFIN, GOLDBERG E VAINBOIM ADVOGADOS ASSOCIADOS (CÍVEL)"

In [0]:
df_fatu_hist = df_fatu_hist.rename(columns={'processo_id': 'PROCESSO - ID', 'data_confirmacao': 'DATA CONFIRMAÇÃO', 'chave_id_status':'CHAVE_ID_STATUS' })

In [0]:
# Converter as colunas e manter os IDs
coluna_int_1 = 'PROCESSO - ID'
coluna_int_2 = '(Processo) ID'

# (pd.to_numeric é mais seguro que .astype(int) pois lida com erros)
df_ger[coluna_int_1] = pd.to_numeric(df_ger[coluna_int_1], errors='coerce')
df_ac[coluna_int_1] = pd.to_numeric(df_ac[coluna_int_1], errors='coerce')
df_fatu_hist[coluna_int_1] = pd.to_numeric(df_fatu_hist[coluna_int_1], errors='coerce')
df_fatu_hist_old[coluna_int_2] = pd.to_numeric(df_fatu_hist_old[coluna_int_2], errors='coerce')

In [0]:
df_ac = df_ac.drop_duplicates(subset=['PROCESSO - ID'], keep='last')
df_fatu_hist = df_fatu_hist.drop_duplicates(subset=['PROCESSO - ID'], keep='last')
df_fatu_hist_old = df_fatu_hist_old.drop_duplicates(subset=['(Processo) ID'], keep='last')

In [0]:
#Realiza o proc entre a tabela Df_ger e a tabela df_ac, trazendo a DATA ACEITE
df_ger_1 = pd.merge(
    df_ger,
    df_ac[['PROCESSO - ID', 'DATA ACEITE']],
    on='PROCESSO - ID',
    how='left'
)

In [0]:
df_ger_1.head()

,PROCESSO - ID,PASTA,GRUPO,ÁREA DO DIREITO,SUB-ÁREA DO DIREITO,ESTEIRA,ASSUNTO (CÍVEL) - PRINCIPAL,ASSUNTO (CÍVEL) - ASSUNTO,DATA REGISTRADO,STATUS,CENTRO DE CUSTO / ÁREA DEMANDANTE - CÓDIGO,EMPRESA,ADVOGADO RESPONSÁVEL,VALOR DA CAUSA,ESFERA,ESTADO,COMARCA,FORO/TRIBUNAL/ÓRGÃO,VARA/ÓRGÃO,AÇÃO,DISTRIBUIÇÃO,NÚMERO DO PROCESSO,PARTE CONTRÁRIA NOME,PARTE CONTRÁRIA CPF,ESCRITÓRIO EXTERNO,Escritório Anterior,FASE,COMPRA DIRETA OU MARKETPLACE? - NEW,USUÁRIO CADASTRANTE,DATA DA BAIXA PROVISÓRIA,DATA DA REATIVAÇÃO,VALOR PROVISIONADO,VALOR PROVISIONADO ATUALIZADO,PROCESSO CRITICO? (CÍVEL),ASSISTENTE JURÍDICO - CÍVEL,ASSISTENTE JURÍDICO -,DATA AUDIENCIA INICIAL,RECLAMAÇÃO BLACK FRIDAY?,OUTRAS PARTES / NÃO-CLIENTES,MOTIVO DA CRITICIDADE,ADVOGADO DA PARTE CONTRÁRIA,DATA DE REABERTURA,DATA DE RECEBIMENTO,PARTE DESCRITA NA INICIAL,TIPO DE CONTINGÊNCIA,ANO DA BLACK FRIDAY,DATA DA ÚLTIMA MOVIMENTAÇÃO PROCESSUAL,OBSERVAÇÕES,OBSERVAÇÃO,TERCEIRO SOLVENTE,INCONTROVERSO (ZERAR PROVISÃO),RESULTADO,DATA DE SOLICITAÇÃO DE ENCERRAMENTO,DATA DE ENCERRAMENTO NO TRIBUNAL,MOTIVO DE ENCERRAMENTO,RECLAMAÇÃO ANTERIOR NO PROCON?,DATA DE REGISTRO DO ENCERRAMENTO,EXISTE PROCESSO COM O MESMO CPF?,CÍVEL MASSA - RESPONSABILIDADE,ESTRATÉGIA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,JUSTIFICATIVA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,CÍVEL MASSA - TIPOS DE TERCEIRO,PARTE CONTRÁRIA DATA ADMISSÃO,PARTE CONTRÁRIA DATA DISPENSA,PARTE CONTRÁRIA - STATUS EM FOLHA,PARTE CONTRÁRIA - MATRICULA,PARTE CONTRÁRIA - CARGO - CARGO (GRUPO),MOTIVO DA BAIXA PROVISÓRIA,PRODUTO,FABRICANTE DO PRODUTO,VALOR DO PRODUTO,PROCESSO - Nº. PEDIDO,DATA DO PEDIDO,LISTA LOJISTA - NOME,LISTA LOJISTA - ID,DATA DA COMPRA,TRANSPORTADORA,NÚMERO DA NOTA FISCAL,SITE DA COMPRA,DATA DO FATO GERADOR,DATA FATO GERADOR,DATA DO FATO GERADOR.1,DATA DO FATO GERADOR.2,INDIQUE A FILIAL,Data da Baixa Provisória,DATA DE REATIVAÇÃO - nativo,DATA DA REATIVAÇÃO -,E-MAIL - PARTE CONTRÁRIA,Processo - RESPONSÁVEL PELA VALIDAÇÃO - AUTOMÁTICO,Processo - RESPONSÁVEL PELA VALIDAÇÃO - MANUAL,PARA QUAL STATUS DESEJA ALTERAR?,MOTIVO DA ALTERAÇÃO DE STATUS,APTO PARA ACORDO?,ILEGITIMIDADE PASSIVA,PROJETO RECORTE MASSA?,Processo - EVENTO - CÍVEL,Processo - POSSUI A INICIAL?,Processo - CARTEIRA ESTRATÉGICO - CIVEL,Processo - MOTIVO DA APTIDÃO ?,PROCESSO - VIA NO POLO,PROCESSO - OBJETO CÍVEL (2) - NEW - SECUNDÁRIO,PROCESSO - OBJETO CÍVEL (2) - NEW - ASSUNTO,FEIRÃO LIMPA NOME,DESENROLA BRASIL,SUBSÍDIOS DISPONIBILIZADOS ATÉ O MOMENTO DE INSERÇÃO DA DEFESA?,APRESENTADA DEFESA GENÉRICA?,CATEGORIZAÇÃO BANQI,GRUPO CASAS BAHIA NO POLO DA AÇÃO?,Processo - DATA DA ABERTURA DE CONTA,PAGAR HONORÁRIOS AO ESCRITÓRIO?,Pedido,ADVOGADO OFENSOR (CÍV. MASSA),CÍVEL MASSA - FLUXO DE RESSARCIMENTO?,SEGUIR COM O PAGAMENTO DE HONORARIOS,DATA ACEITE
0,289797,CIV.23267,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),ENTREGA E MONTAGEM,ENTREGA DE PRODUTO DIVERSO - EM,2016-06-07,BAIXA PROVISORIA,2114013051.00,GRUPO CASAS BAHIA S/A,FELIPPE SILVA FOGAZZA,21720.00,JUDICIAL,RJ,NOVA IGUAÇÚ,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,7ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-05-14,'00505448220148190038,KEROLLYN DE OLIVEIRA VIRLA,N/I,LAURO RABHA,NaN,CUMPRIMENTO DE SENTENÇA,NaN,GUILHERME SPAMER,2024-07-08 14:49:15.126,NaT,0,0.00,NÃO,NAYARA CARLA DE SOUSA,LEONARDO PAULO LOMBARDI RODRIGUES - CNOVA,NaN,NaN,ADVOGADO ADVERSO - TATIANA BASTOS DE MELLO,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,NaT,NaN,PASSIVO,NaN,NaT,NaN,PROCESSOS ENCERRADOS POR BANCO CONFORME ANALISE FEITA EM PLANILHA ENVIADA A GERENCIA DO PLANEJAM...,NaN,NaN,PARCIALMENTE PROCEDENTE,2019-04-12 00:00:00,2020-11-04,CONDENAÇÃO COM OBF E PAGAMENTO,NaN,2020-11-04,NaN,NaN,ACORDO,DECISÃO DESFAVORÁVEL,LEGADO,NaT,NaT,NaN,NaN,NaN,NaN,ARMÁRIO MULTIUSO,BARTIRA,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2024-07-08 14:49:15.126,NaN,NaT,NaN,NaN,NaN,2 - DE ENCERRADO PARA BAIXA PROVISÓRIA,CUSTAS REMANESCENTE,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,2024-12-06
1,317446,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,JEC,MASSA (CÍVEL),VENDA DE CARTEIRA DE CRÉDITO,VENDA DE CARTEIRA DE CRÉDITO - VCC,2016-10-13,BAIXA PROVISORIA,2106503025.00,GLOBEX UTILIDADES S/A (GPA),FELIPPE SILVA FOGAZZA,40000.00,JUDICIAL,RJ,RIO DE JANEIRO,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,20ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-09-16,00176673020158190208,MARCELO PASCHOAL DE OLIVEIRA,068.477.487-96,LAURO RABHA,QUEIROZ E LAUTENSCHLAGER (CÍVEL),RECURSAL,NÃO SE APLICA,YNAIA OLIVEIRA DA SILVA - CNOVA,2021-06-28 00:00:00.000,NaT,0,0.00,NÃO,NAYARA CARLA DE SOUSA,LEONARDO PAULO LOMBARDI RODRIGUES - CNOVA,2016-10-18 14:20:00,NÃO,NaN,NaN,RENATO FRANCISCO DA SILVA NETO,2018-08-29 20:06:09.910,2016-10-03,NaN,PASSIVO,NaN,NaT,NaN,NaN,NÃO SE APLICA,NaN,NaN,2019-10-04 14:46:39,NaT,NaN,NÃO,NaT,NaN,NaN,ACORDO,DECISÃO DESFAVORÁVEL,VENDA DE CARTEIRA DE CRÉDITO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,NaT,NaN,NaN,NaN,NaN,NaT,1998-10-25,NaN,NaN,2021-06-28 00:00:00.000,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DANOS MORAIS,NaN,NaN,NÃO SE APLICA,2024-12-06
2,290822,CIV.24393,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),VÍCIO DO PRODUTO,PRODUTO DE TERCEIROS,2016-08-29,REATIVADO,2112003054.00,GRUPO CASAS BAHIA S/A,ROBERTA LUANA ROCHA,116694.50,JUDICIAL,BA,JUAZEIRO,TRIBUNAL DE JUSTIÇA DO ESTADO DA BAHIA,2ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-08-15,'09618686420158050146,MARIA SANDRA LIMA SILVA,N/I,QUEIROZ CAVALCANTI ADVOGADOS,NaN,CONHECIMENTO,NaN,GUILHERME SPAMER,2024-04-09 16:45:28.054,NaT,3168,5069.59,NÃO,GABRIEL GALDINO DE OLIVEIRA,MARIANA LAMEIRA E SILVA,NaN,NaN,NaN,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,NaT,NaN,PASSIVO,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NaN,CASAS BAHIA,ACORDO,AUSÊNCIA DE SUBSÍDIOS,FORNECEDOR,NaT,NaT,NaN,NaN,NaN,PAGAMENTO,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2024-04-09 16:45:28.054,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,ESTRATÉGIA,NaN,NaN,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,2024-12-18
3,84996,JEC.217184GPA,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,JEC,MASSA (CÍVEL),ENTREGA E MONTAGEM,AUSÊNCIA DE ENTREGA - EM,2016-06-09,REATIVADO,2117920206.00,CASAS BAHIA ONLINE,ROBERTA LUANA ROCHA,807.04,JUDICIAL,AL,IGREJA NOVA,TRIBUNAL DE JUSTIÇA DO ESTADO DE ALAGOAS,JEC,AÇÃO DE INDENIZAÇÃO,2016-02-18,0700251-79.2015.8.02.0014,JOE JANIO DE OLIVEIRA DAVINO,055.833.364-80,QUEIROZ CAVALCANTI ADVOGADOS,NaN,EXECUÇÃO,MARKETPLACE,GUILHERME SPAMER,2018-05-23 00:00:00.000,NaT,3913,6261.78,NÃO,GABRIEL GALDINO DE OLIVEIRA,MARIANA LAMEIRA E SILVA,NaN,NÃO,NaN,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,2024-04-23,NaN,PASSIVO,NaN,NaT,NaN,NaN,NÃO SE APLICA,NaN,AUSÊNCIA DO AUTOR,NaT,2018-05-23,AUSÊNCIA DO AUTOR,NaN,NaT,NÃO,NaN,ACORDO,AUSÊNCIA DE SUBSÍDIOS,NÃO É TERCEIRO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2018-05-23 00:00:00.000,NaN,2024-04-15 18:19:25.459,NaN,NaN,NaN,4 - DE ENCERRADO PARA REATIVADO,4.1 - EXECUÇÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,SIM,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,2024-12-18
4,305154,JEC.222054,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),CRÉDITO E COBRANÇA,CARTÃO PF - COBRANÇA INDEVIDA COM NEGATIVAÇÃO,2016-05-31,REATIVADO,2106500311.00,GRUPO CASAS BAHIA S/A,JENIFFER CONCEICAO DE SOUZA,3006.80,JUDICIAL,SC,JOINVILLE,TRIBUNAL DE JUSTIÇA DO ESTADO DE SANTA CATARINA,2ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2015-09-08,0017211-67.2015.8.24.0038,VERA LUCIA CALVO,491.659.179-87,PINTO & SOARES ADVOGADOS ASSOCIADOS,NaN,CONHECIMENTO,DIRETA,GUILHERME SPAMER,NaT,NaT,0,0.00,NÃO,RAFAEL EPISCOPO RODRIGUES COSTA,WEVERTON SOUZA MATOS,NaN,NÃO,TERCEIRO - BANCO ITAUCRED,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,2019-10-23,VIA VAREJO,PASSIVO,NaN,NaT,NaN,NaN,ITAÚ,NaN,SANEAMENTO - MENDES E BARRETO,NaT,2025-06-27,SANEAMENTO - MENDES E BARRETO,NÃO,NaT,NaN,TERCEIROS,ACORDO,DECISÃO DESFAVORÁVEL,CARTÃO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,NaT,NaN,NaN,NaN,NaN,NaT,2015-09-08,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,SIM,NÃO,NaN,NaN,NaN,NaN,ESTRATÉGIA,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM,NÃO SE APLICA,2024-12-04

In [0]:
df_ger_1 = df_ger_1.rename(columns={'DATA ACEITE': 'DATA DO ACEITE'})

In [0]:
#Realiza o map e completa as linhas nulas do DATA ACEITE, 
# Com a DATA CONFIRMAÇÃO do hist de faturamento onde existe relação entre os IDs

mapa_de_datas = df_fatu_hist.set_index('PROCESSO - ID')['DATA CONFIRMAÇÃO']

df_ger_1['DATA DO ACEITE'] = df_ger_1['DATA DO ACEITE'].fillna(df_ger_1['PROCESSO - ID'].map(mapa_de_datas))

In [0]:
df_ger_1.head()

,PROCESSO - ID,PASTA,GRUPO,ÁREA DO DIREITO,SUB-ÁREA DO DIREITO,ESTEIRA,ASSUNTO (CÍVEL) - PRINCIPAL,ASSUNTO (CÍVEL) - ASSUNTO,DATA REGISTRADO,STATUS,CENTRO DE CUSTO / ÁREA DEMANDANTE - CÓDIGO,EMPRESA,ADVOGADO RESPONSÁVEL,VALOR DA CAUSA,ESFERA,ESTADO,COMARCA,FORO/TRIBUNAL/ÓRGÃO,VARA/ÓRGÃO,AÇÃO,DISTRIBUIÇÃO,NÚMERO DO PROCESSO,PARTE CONTRÁRIA NOME,PARTE CONTRÁRIA CPF,ESCRITÓRIO EXTERNO,Escritório Anterior,FASE,COMPRA DIRETA OU MARKETPLACE? - NEW,USUÁRIO CADASTRANTE,DATA DA BAIXA PROVISÓRIA,DATA DA REATIVAÇÃO,VALOR PROVISIONADO,VALOR PROVISIONADO ATUALIZADO,PROCESSO CRITICO? (CÍVEL),ASSISTENTE JURÍDICO - CÍVEL,ASSISTENTE JURÍDICO -,DATA AUDIENCIA INICIAL,RECLAMAÇÃO BLACK FRIDAY?,OUTRAS PARTES / NÃO-CLIENTES,MOTIVO DA CRITICIDADE,ADVOGADO DA PARTE CONTRÁRIA,DATA DE REABERTURA,DATA DE RECEBIMENTO,PARTE DESCRITA NA INICIAL,TIPO DE CONTINGÊNCIA,ANO DA BLACK FRIDAY,DATA DA ÚLTIMA MOVIMENTAÇÃO PROCESSUAL,OBSERVAÇÕES,OBSERVAÇÃO,TERCEIRO SOLVENTE,INCONTROVERSO (ZERAR PROVISÃO),RESULTADO,DATA DE SOLICITAÇÃO DE ENCERRAMENTO,DATA DE ENCERRAMENTO NO TRIBUNAL,MOTIVO DE ENCERRAMENTO,RECLAMAÇÃO ANTERIOR NO PROCON?,DATA DE REGISTRO DO ENCERRAMENTO,EXISTE PROCESSO COM O MESMO CPF?,CÍVEL MASSA - RESPONSABILIDADE,ESTRATÉGIA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,JUSTIFICATIVA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,CÍVEL MASSA - TIPOS DE TERCEIRO,PARTE CONTRÁRIA DATA ADMISSÃO,PARTE CONTRÁRIA DATA DISPENSA,PARTE CONTRÁRIA - STATUS EM FOLHA,PARTE CONTRÁRIA - MATRICULA,PARTE CONTRÁRIA - CARGO - CARGO (GRUPO),MOTIVO DA BAIXA PROVISÓRIA,PRODUTO,FABRICANTE DO PRODUTO,VALOR DO PRODUTO,PROCESSO - Nº. PEDIDO,DATA DO PEDIDO,LISTA LOJISTA - NOME,LISTA LOJISTA - ID,DATA DA COMPRA,TRANSPORTADORA,NÚMERO DA NOTA FISCAL,SITE DA COMPRA,DATA DO FATO GERADOR,DATA FATO GERADOR,DATA DO FATO GERADOR.1,DATA DO FATO GERADOR.2,INDIQUE A FILIAL,Data da Baixa Provisória,DATA DE REATIVAÇÃO - nativo,DATA DA REATIVAÇÃO -,E-MAIL - PARTE CONTRÁRIA,Processo - RESPONSÁVEL PELA VALIDAÇÃO - AUTOMÁTICO,Processo - RESPONSÁVEL PELA VALIDAÇÃO - MANUAL,PARA QUAL STATUS DESEJA ALTERAR?,MOTIVO DA ALTERAÇÃO DE STATUS,APTO PARA ACORDO?,ILEGITIMIDADE PASSIVA,PROJETO RECORTE MASSA?,Processo - EVENTO - CÍVEL,Processo - POSSUI A INICIAL?,Processo - CARTEIRA ESTRATÉGICO - CIVEL,Processo - MOTIVO DA APTIDÃO ?,PROCESSO - VIA NO POLO,PROCESSO - OBJETO CÍVEL (2) - NEW - SECUNDÁRIO,PROCESSO - OBJETO CÍVEL (2) - NEW - ASSUNTO,FEIRÃO LIMPA NOME,DESENROLA BRASIL,SUBSÍDIOS DISPONIBILIZADOS ATÉ O MOMENTO DE INSERÇÃO DA DEFESA?,APRESENTADA DEFESA GENÉRICA?,CATEGORIZAÇÃO BANQI,GRUPO CASAS BAHIA NO POLO DA AÇÃO?,Processo - DATA DA ABERTURA DE CONTA,PAGAR HONORÁRIOS AO ESCRITÓRIO?,Pedido,ADVOGADO OFENSOR (CÍV. MASSA),CÍVEL MASSA - FLUXO DE RESSARCIMENTO?,SEGUIR COM O PAGAMENTO DE HONORARIOS,DATA DO ACEITE
0,289797,CIV.23267,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),ENTREGA E MONTAGEM,ENTREGA DE PRODUTO DIVERSO - EM,2016-06-07,BAIXA PROVISORIA,2114013051.00,GRUPO CASAS BAHIA S/A,FELIPPE SILVA FOGAZZA,21720.00,JUDICIAL,RJ,NOVA IGUAÇÚ,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,7ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-05-14,'00505448220148190038,KEROLLYN DE OLIVEIRA VIRLA,N/I,LAURO RABHA,NaN,CUMPRIMENTO DE SENTENÇA,NaN,GUILHERME SPAMER,2024-07-08 14:49:15.126,NaT,0,0.00,NÃO,NAYARA CARLA DE SOUSA,LEONARDO PAULO LOMBARDI RODRIGUES - CNOVA,NaN,NaN,ADVOGADO ADVERSO - TATIANA BASTOS DE MELLO,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,NaT,NaN,PASSIVO,NaN,NaT,NaN,PROCESSOS ENCERRADOS POR BANCO CONFORME ANALISE FEITA EM PLANILHA ENVIADA A GERENCIA DO PLANEJAM...,NaN,NaN,PARCIALMENTE PROCEDENTE,2019-04-12 00:00:00,2020-11-04,CONDENAÇÃO COM OBF E PAGAMENTO,NaN,2020-11-04,NaN,NaN,ACORDO,DECISÃO DESFAVORÁVEL,LEGADO,NaT,NaT,NaN,NaN,NaN,NaN,ARMÁRIO MULTIUSO,BARTIRA,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2024-07-08 14:49:15.126,NaN,NaT,NaN,NaN,NaN,2 - DE ENCERRADO PARA BAIXA PROVISÓRIA,CUSTAS REMANESCENTE,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,2024-12-06 00:00:00
1,317446,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,JEC,MASSA (CÍVEL),VENDA DE CARTEIRA DE CRÉDITO,VENDA DE CARTEIRA DE CRÉDITO - VCC,2016-10-13,BAIXA PROVISORIA,2106503025.00,GLOBEX UTILIDADES S/A (GPA),FELIPPE SILVA FOGAZZA,40000.00,JUDICIAL,RJ,RIO DE JANEIRO,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,20ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-09-16,00176673020158190208,MARCELO PASCHOAL DE OLIVEIRA,068.477.487-96,LAURO RABHA,QUEIROZ E LAUTENSCHLAGER (CÍVEL),RECURSAL,NÃO SE APLICA,YNAIA OLIVEIRA DA SILVA - CNOVA,2021-06-28 00:00:00.000,NaT,0,0.00,NÃO,NAYARA CARLA DE SOUSA,LEONARDO PAULO LOMBARDI RODRIGUES - CNOVA,2016-10-18 14:20:00,NÃO,NaN,NaN,RENATO FRANCISCO DA SILVA NETO,2018-08-29 20:06:09.910,2016-10-03,NaN,PASSIVO,NaN,NaT,NaN,NaN,NÃO SE APLICA,NaN,NaN,2019-10-04 14:46:39,NaT,NaN,NÃO,NaT,NaN,NaN,ACORDO,DECISÃO DESFAVORÁVEL,VENDA DE CARTEIRA DE CRÉDITO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,NaT,NaN,NaN,NaN,NaN,NaT,1998-10-25,NaN,NaN,2021-06-28 00:00:00.000,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DANOS MORAIS,NaN,NaN,NÃO SE APLICA,2024-12-06 00:00:00
2,290822,CIV.24393,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),VÍCIO DO PRODUTO,PRODUTO DE TERCEIROS,2016-08-29,REATIVADO,2112003054.00,GRUPO CASAS BAHIA S/A,ROBERTA LUANA ROCHA,116694.50,JUDICIAL,BA,JUAZEIRO,TRIBUNAL DE JUSTIÇA DO ESTADO DA BAHIA,2ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-08-15,'09618686420158050146,MARIA SANDRA LIMA SILVA,N/I,QUEIROZ CAVALCANTI ADVOGADOS,NaN,CONHECIMENTO,NaN,GUILHERME SPAMER,2024-04-09 16:45:28.054,NaT,3168,5069.59,NÃO,GABRIEL GALDINO DE OLIVEIRA,MARIANA LAMEIRA E SILVA,NaN,NaN,NaN,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,NaT,NaN,PASSIVO,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NaN,CASAS BAHIA,ACORDO,AUSÊNCIA DE SUBSÍDIOS,FORNECEDOR,NaT,NaT,NaN,NaN,NaN,PAGAMENTO,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2024-04-09 16:45:28.054,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,ESTRATÉGIA,NaN,NaN,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,2024-12-18 00:00:00
3,84996,JEC.217184GPA,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,JEC,MASSA (CÍVEL),ENTREGA E MONTAGEM,AUSÊNCIA DE ENTREGA - EM,2016-06-09,REATIVADO,2117920206.00,CASAS BAHIA ONLINE,ROBERTA LUANA ROCHA,807.04,JUDICIAL,AL,IGREJA NOVA,TRIBUNAL DE JUSTIÇA DO ESTADO DE ALAGOAS,JEC,AÇÃO DE INDENIZAÇÃO,2016-02-18,0700251-79.2015.8.02.0014,JOE JANIO DE OLIVEIRA DAVINO,055.833.364-80,QUEIROZ CAVALCANTI ADVOGADOS,NaN,EXECUÇÃO,MARKETPLACE,GUILHERME SPAMER,2018-05-23 00:00:00.000,NaT,3913,6261.78,NÃO,GABRIEL GALDINO DE OLIVEIRA,MARIANA LAMEIRA E SILVA,NaN,NÃO,NaN,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,2024-04-23,NaN,PASSIVO,NaN,NaT,NaN,NaN,NÃO SE APLICA,NaN,AUSÊNCIA DO AUTOR,NaT,2018-05-23,AUSÊNCIA DO AUTOR,NaN,NaT,NÃO,NaN,ACORDO,AUSÊNCIA DE SUBSÍDIOS,NÃO É TERCEIRO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2018-05-23 00:00:00.000,NaN,2024-04-15 18:19:25.459,NaN,NaN,NaN,4 - DE ENCERRADO PARA REATIVADO,4.1 - EXECUÇÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,SIM,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,2024-12-18 00:00:00
4,305154,JEC.222054,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),CRÉDITO E COBRANÇA,CARTÃO PF - COBRANÇA INDEVIDA COM NEGATIVAÇÃO,2016-05-31,REATIVADO,2106500311.00,GRUPO CASAS BAHIA S/A,JENIFFER CONCEICAO DE SOUZA,3006.80,JUDICIAL,SC,JOINVILLE,TRIBUNAL DE JUSTIÇA DO ESTADO DE SANTA CATARINA,2ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2015-09-08,0017211-67.2015.8.24.0038,VERA LUCIA CALVO,491.659.179-87,PINTO & SOARES ADVOGADOS ASSOCIADOS,NaN,CONHECIMENTO,DIRETA,GUILHERME SPAMER,NaT,NaT,0,0.00,NÃO,RAFAEL EPISCOPO RODRIGUES COSTA,WEVERTON SOUZA MATOS,NaN,NÃO,TERCEIRO - BANCO ITAUCRED,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,2019-10-23,VIA VAREJO,PASSIVO,NaN,NaT,NaN,NaN,ITAÚ,NaN,SANEAMENTO - MENDES E BARRETO,NaT,2025-06-27,SANEAMENTO - MENDES E BARRETO,NÃO,NaT,NaN,TERCEIROS,ACORDO,DECISÃO DESFAVORÁVEL,CARTÃO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,NaT,NaN,NaN,NaN,NaN,NaT,2015-09-08,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,SIM,NÃO,NaN,NaN,NaN,NaN,ESTRATÉGIA,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM,NÃO SE APLICA,2024-12-04 00:00:00

In [0]:
# Realiza o map e completa as linhas nulas do DATA ACEITE, seguindo a regra de que a DATA ACEITE é null e o STATUS é PRÉ CADASTRO

cond_vazia = df_ger_1['DATA DO ACEITE'].isnull()
cond_status = df_ger_1['STATUS'] == 'PRÉ CADASTRO'

df_ger_1.loc[cond_vazia & cond_status, 'DATA DO ACEITE'] = "sem data aceite"

In [0]:
#primeiro será necessário converter a coluna DATA REGISTRO para datetime

df_ger_1['DATA REGISTRADO'] = pd.to_datetime(df_ger_1['DATA REGISTRADO'], errors='coerce')
cond_vazia = df_ger_1['DATA DO ACEITE'].isnull()

#Segundo passo é filtrar os registros que estão no mês SELECIONADO
cond_meses = df_ger_1['DATA REGISTRADO'].dt.month.isin([11,12,1]) #<===== MUDAR TODOS OS MESES A MEDIDA DO MES DO FATURAMENTO

#terceiro passo é aplicar a regra de que a DATA ACEITE é null e a data registro está entre os meses SELECIONADOS
df_ger_1.loc[cond_vazia & cond_meses, 'DATA DO ACEITE'] = "sem data aceite"

In [0]:
#Agora os que subraram como null pela regra devem ser clasificados como "com data aceite"
df_ger_1['DATA DO ACEITE'] = df_ger_1['DATA DO ACEITE'].fillna("com data aceite")

In [0]:
#ESCREVE NA NOVA COLUNA STATUS_1 TUDO QUE ESTIVER SEM DATA ACEITE ESCREVE NA COLUNA STATUS_1 = 'Não Faturar - Sem Data Aceite'

df_ger_1['STATUS_1'] = ''
cond1 = df_ger_1['DATA DO ACEITE'] == 'sem data aceite'
df_ger_1.loc[cond1, 'STATUS_1'] = 'Não Faturar - Sem Data Aceite'

In [0]:
id_str = df_ger_1['PROCESSO - ID'].astype(str).str.replace(r'\.0$', '', regex=True)
escrit_str = df_ger_1['ESCRITÓRIO EXTERNO'].astype(str)

df_ger_1['Nova_Coluna'] = (
    id_str + 'ENCERRADO' + escrit_str
)

In [0]:
df_ger_1.head()

,PROCESSO - ID,PASTA,GRUPO,ÁREA DO DIREITO,SUB-ÁREA DO DIREITO,ESTEIRA,ASSUNTO (CÍVEL) - PRINCIPAL,ASSUNTO (CÍVEL) - ASSUNTO,DATA REGISTRADO,STATUS,CENTRO DE CUSTO / ÁREA DEMANDANTE - CÓDIGO,EMPRESA,ADVOGADO RESPONSÁVEL,VALOR DA CAUSA,ESFERA,ESTADO,COMARCA,FORO/TRIBUNAL/ÓRGÃO,VARA/ÓRGÃO,AÇÃO,DISTRIBUIÇÃO,NÚMERO DO PROCESSO,PARTE CONTRÁRIA NOME,PARTE CONTRÁRIA CPF,ESCRITÓRIO EXTERNO,Escritório Anterior,FASE,COMPRA DIRETA OU MARKETPLACE? - NEW,USUÁRIO CADASTRANTE,DATA DA BAIXA PROVISÓRIA,DATA DA REATIVAÇÃO,VALOR PROVISIONADO,VALOR PROVISIONADO ATUALIZADO,PROCESSO CRITICO? (CÍVEL),ASSISTENTE JURÍDICO - CÍVEL,ASSISTENTE JURÍDICO -,DATA AUDIENCIA INICIAL,RECLAMAÇÃO BLACK FRIDAY?,OUTRAS PARTES / NÃO-CLIENTES,MOTIVO DA CRITICIDADE,ADVOGADO DA PARTE CONTRÁRIA,DATA DE REABERTURA,DATA DE RECEBIMENTO,PARTE DESCRITA NA INICIAL,TIPO DE CONTINGÊNCIA,ANO DA BLACK FRIDAY,DATA DA ÚLTIMA MOVIMENTAÇÃO PROCESSUAL,OBSERVAÇÕES,OBSERVAÇÃO,TERCEIRO SOLVENTE,INCONTROVERSO (ZERAR PROVISÃO),RESULTADO,DATA DE SOLICITAÇÃO DE ENCERRAMENTO,DATA DE ENCERRAMENTO NO TRIBUNAL,MOTIVO DE ENCERRAMENTO,RECLAMAÇÃO ANTERIOR NO PROCON?,DATA DE REGISTRO DO ENCERRAMENTO,EXISTE PROCESSO COM O MESMO CPF?,CÍVEL MASSA - RESPONSABILIDADE,ESTRATÉGIA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,JUSTIFICATIVA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,CÍVEL MASSA - TIPOS DE TERCEIRO,PARTE CONTRÁRIA DATA ADMISSÃO,PARTE CONTRÁRIA DATA DISPENSA,PARTE CONTRÁRIA - STATUS EM FOLHA,PARTE CONTRÁRIA - MATRICULA,PARTE CONTRÁRIA - CARGO - CARGO (GRUPO),MOTIVO DA BAIXA PROVISÓRIA,PRODUTO,FABRICANTE DO PRODUTO,VALOR DO PRODUTO,PROCESSO - Nº. PEDIDO,DATA DO PEDIDO,LISTA LOJISTA - NOME,LISTA LOJISTA - ID,DATA DA COMPRA,TRANSPORTADORA,NÚMERO DA NOTA FISCAL,SITE DA COMPRA,DATA DO FATO GERADOR,DATA FATO GERADOR,DATA DO FATO GERADOR.1,DATA DO FATO GERADOR.2,INDIQUE A FILIAL,Data da Baixa Provisória,DATA DE REATIVAÇÃO - nativo,DATA DA REATIVAÇÃO -,E-MAIL - PARTE CONTRÁRIA,Processo - RESPONSÁVEL PELA VALIDAÇÃO - AUTOMÁTICO,Processo - RESPONSÁVEL PELA VALIDAÇÃO - MANUAL,PARA QUAL STATUS DESEJA ALTERAR?,MOTIVO DA ALTERAÇÃO DE STATUS,APTO PARA ACORDO?,ILEGITIMIDADE PASSIVA,PROJETO RECORTE MASSA?,Processo - EVENTO - CÍVEL,Processo - POSSUI A INICIAL?,Processo - CARTEIRA ESTRATÉGICO - CIVEL,Processo - MOTIVO DA APTIDÃO ?,PROCESSO - VIA NO POLO,PROCESSO - OBJETO CÍVEL (2) - NEW - SECUNDÁRIO,PROCESSO - OBJETO CÍVEL (2) - NEW - ASSUNTO,FEIRÃO LIMPA NOME,DESENROLA BRASIL,SUBSÍDIOS DISPONIBILIZADOS ATÉ O MOMENTO DE INSERÇÃO DA DEFESA?,APRESENTADA DEFESA GENÉRICA?,CATEGORIZAÇÃO BANQI,GRUPO CASAS BAHIA NO POLO DA AÇÃO?,Processo - DATA DA ABERTURA DE CONTA,PAGAR HONORÁRIOS AO ESCRITÓRIO?,Pedido,ADVOGADO OFENSOR (CÍV. MASSA),CÍVEL MASSA - FLUXO DE RESSARCIMENTO?,SEGUIR COM O PAGAMENTO DE HONORARIOS,DATA DO ACEITE,STATUS_1,Nova_Coluna
0,289797,CIV.23267,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),ENTREGA E MONTAGEM,ENTREGA DE PRODUTO DIVERSO - EM,2016-06-07,BAIXA PROVISORIA,2114013051.00,GRUPO CASAS BAHIA S/A,FELIPPE SILVA FOGAZZA,21720.00,JUDICIAL,RJ,NOVA IGUAÇÚ,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,7ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-05-14,'00505448220148190038,KEROLLYN DE OLIVEIRA VIRLA,N/I,LAURO RABHA,NaN,CUMPRIMENTO DE SENTENÇA,NaN,GUILHERME SPAMER,2024-07-08 14:49:15.126,NaT,0,0.00,NÃO,NAYARA CARLA DE SOUSA,LEONARDO PAULO LOMBARDI RODRIGUES - CNOVA,NaN,NaN,ADVOGADO ADVERSO - TATIANA BASTOS DE MELLO,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,NaT,NaN,PASSIVO,NaN,NaT,NaN,PROCESSOS ENCERRADOS POR BANCO CONFORME ANALISE FEITA EM PLANILHA ENVIADA A GERENCIA DO PLANEJAM...,NaN,NaN,PARCIALMENTE PROCEDENTE,2019-04-12 00:00:00,2020-11-04,CONDENAÇÃO COM OBF E PAGAMENTO,NaN,2020-11-04,NaN,NaN,ACORDO,DECISÃO DESFAVORÁVEL,LEGADO,NaT,NaT,NaN,NaN,NaN,NaN,ARMÁRIO MULTIUSO,BARTIRA,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2024-07-08 14:49:15.126,NaN,NaT,NaN,NaN,NaN,2 - DE ENCERRADO PARA BAIXA PROVISÓRIA,CUSTAS REMANESCENTE,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,2024-12-06 00:00:00,,289797ENCERRADOLAURO RABHA
1,317446,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,JEC,MASSA (CÍVEL),VENDA DE CARTEIRA DE CRÉDITO,VENDA DE CARTEIRA DE CRÉDITO - VCC,2016-10-13,BAIXA PROVISORIA,2106503025.00,GLOBEX UTILIDADES S/A (GPA),FELIPPE SILVA FOGAZZA,40000.00,JUDICIAL,RJ,RIO DE JANEIRO,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,20ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-09-16,00176673020158190208,MARCELO PASCHOAL DE OLIVEIRA,068.477.487-96,LAURO RABHA,QUEIROZ E LAUTENSCHLAGER (CÍVEL),RECURSAL,NÃO SE APLICA,YNAIA OLIVEIRA DA SILVA - CNOVA,2021-06-28 00:00:00.000,NaT,0,0.00,NÃO,NAYARA CARLA DE SOUSA,LEONARDO PAULO LOMBARDI RODRIGUES - CNOVA,2016-10-18 14:20:00,NÃO,NaN,NaN,RENATO FRANCISCO DA SILVA NETO,2018-08-29 20:06:09.910,2016-10-03,NaN,PASSIVO,NaN,NaT,NaN,NaN,NÃO SE APLICA,NaN,NaN,2019-10-04 14:46:39,NaT,NaN,NÃO,NaT,NaN,NaN,ACORDO,DECISÃO DESFAVORÁVEL,VENDA DE CARTEIRA DE CRÉDITO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,NaT,NaN,NaN,NaN,NaN,NaT,1998-10-25,NaN,NaN,2021-06-28 00:00:00.000,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DANOS MORAIS,NaN,NaN,NÃO SE APLICA,2024-12-06 00:00:00,,317446ENCERRADOLAURO RABHA
2,290822,CIV.24393,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),VÍCIO DO PRODUTO,PRODUTO DE TERCEIROS,2016-08-29,REATIVADO,2112003054.00,GRUPO CASAS BAHIA S/A,ROBERTA LUANA ROCHA,116694.50,JUDICIAL,BA,JUAZEIRO,TRIBUNAL DE JUSTIÇA DO ESTADO DA BAHIA,2ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-08-15,'09618686420158050146,MARIA SANDRA LIMA SILVA,N/I,QUEIROZ CAVALCANTI ADVOGADOS,NaN,CONHECIMENTO,NaN,GUILHERME SPAMER,2024-04-09 16:45:28.054,NaT,3168,5069.59,NÃO,GABRIEL GALDINO DE OLIVEIRA,MARIANA LAMEIRA E SILVA,NaN,NaN,NaN,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,NaT,NaN,PASSIVO,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NaN,CASAS BAHIA,ACORDO,AUSÊNCIA DE SUBSÍDIOS,FORNECEDOR,NaT,NaT,NaN,NaN,NaN,PAGAMENTO,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2024-04-09 16:45:28.054,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,ESTRATÉGIA,NaN,NaN,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,2024-12-18 00:00:00,,290822ENCERRADOQUEIROZ CAVALCANTI ADVOGADOS
3,84996,JEC.217184GPA,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,JEC,MASSA (CÍVEL),ENTREGA E MONTAGEM,AUSÊNCIA DE ENTREGA - EM,2016-06-09,REATIVADO,2117920206.00,CASAS BAHIA ONLINE,ROBERTA LUANA ROCHA,807.04,JUDICIAL,AL,IGREJA NOVA,TRIBUNAL DE JUSTIÇA DO ESTADO DE ALAGOAS,JEC,AÇÃO DE INDENIZAÇÃO,2016-02-18,0700251-79.2015.8.02.0014,JOE JANIO DE OLIVEIRA DAVINO,055.833.364-80,QUEIROZ CAVALCANTI ADVOGADOS,NaN,EXECUÇÃO,MARKETPLACE,GUILHERME SPAMER,2018-05-23 00:00:00.000,NaT,3913,6261.78,NÃO,GABRIEL GALDINO DE OLIVEIRA,MARIANA LAMEIRA E SILVA,NaN,NÃO,NaN,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,2024-04-23,NaN,PASSIVO,NaN,NaT,NaN,NaN,NÃO SE APLICA,NaN,AUSÊNCIA DO AUTOR,NaT,2018-05-23,AUSÊNCIA DO AUTOR,NaN,NaT,NÃO,NaN,ACORDO,AUSÊNCIA DE SUBSÍDIOS,NÃO É TERCEIRO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2018-05-23 00:00:00.000,NaN,2024-04-15 18:19:25.459,NaN,NaN,NaN,4 - DE ENCERRADO PARA REATIVADO,4.1 - EXECUÇÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,SIM,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,2024-12-18 00:00:00,,84996ENCERRADOQUEIROZ CAVALCANTI ADVOGADOS
4,305154,JEC.222054,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),CRÉDITO E COBRANÇA,CARTÃO PF - COBRANÇA INDEVIDA COM NEGATIVAÇÃO,2016-05-31,REATIVADO,2106500311.00,GRUPO CASAS BAHIA S/A,JENIFFER CONCEICAO DE SOUZA,3006.80,JUDICIAL,SC,JOINVILLE,TRIBUNAL DE JUSTIÇA DO ESTADO DE SANTA CATARINA,2ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2015-09-08,0017211-67.2015.8.24.0038,VERA LUCIA CALVO,491.659.179-87,PINTO & SOARES ADVOGADOS ASSOCIADOS,NaN,CONHECIMENTO,DIRETA,GUILHERME SPAMER,NaT,NaT,0,0.00,NÃO,RAFAEL EPISCOPO RODRIGUES COSTA,WEVERTON SOUZA MATOS,NaN,NÃO,TERCEIRO - BANCO ITAUCRED,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,2019-10-23,VIA VAREJO,PASSIVO,NaN,NaT,NaN,NaN,ITAÚ,NaN,SANEAMENTO - MENDES E BARRETO,NaT,2025-06-27,SANEAMENTO - MENDES E BARRETO,NÃO,NaT,NaN,TERCEIROS,ACORDO,DECISÃO DESFAVORÁVEL,CARTÃO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,NaT,NaN,NaN,NaN,NaN,NaT,2015-09-08,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,SIM,NÃO,NaN,NaN,NaN,NaN,ESTRATÉGIA,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM,NÃO SE APLICA,2024-12-04 00:00:00,,305154ENCERRADOPINTO & SOARES ADVOGADOS ASSOCIADOS

In [0]:
#renomeia coluna concatenada para não dar erro

df_fatu_hist.rename(columns={'Chave (ID + STATUS)': 'CHAVE_ID_STATUS'}, inplace=True)

df_fatu_hist.columns = df_fatu_hist.columns.str.strip()

In [0]:
#Dropa as chaves iguais mantandendo a última atualização

df_fatu_hist = df_fatu_hist.drop_duplicates(subset=['CHAVE_ID_STATUS'], keep='last')

In [0]:
#Traz a coluna CHAVE_ID_STATUS e relaciona as correpondencias, se nãp houver, o valor fica nulo
df_resumido = df_fatu_hist[['CHAVE_ID_STATUS']]
df_ger_1 = pd.merge(
    df_ger_1,
    df_resumido,
    left_on='Nova_Coluna',
    right_on='CHAVE_ID_STATUS',
    how='left'
)

In [0]:
df_ger_1.head()

,PROCESSO - ID,PASTA,GRUPO,ÁREA DO DIREITO,SUB-ÁREA DO DIREITO,ESTEIRA,ASSUNTO (CÍVEL) - PRINCIPAL,ASSUNTO (CÍVEL) - ASSUNTO,DATA REGISTRADO,STATUS,CENTRO DE CUSTO / ÁREA DEMANDANTE - CÓDIGO,EMPRESA,ADVOGADO RESPONSÁVEL,VALOR DA CAUSA,ESFERA,ESTADO,COMARCA,FORO/TRIBUNAL/ÓRGÃO,VARA/ÓRGÃO,AÇÃO,DISTRIBUIÇÃO,NÚMERO DO PROCESSO,PARTE CONTRÁRIA NOME,PARTE CONTRÁRIA CPF,ESCRITÓRIO EXTERNO,Escritório Anterior,FASE,COMPRA DIRETA OU MARKETPLACE? - NEW,USUÁRIO CADASTRANTE,DATA DA BAIXA PROVISÓRIA,DATA DA REATIVAÇÃO,VALOR PROVISIONADO,VALOR PROVISIONADO ATUALIZADO,PROCESSO CRITICO? (CÍVEL),ASSISTENTE JURÍDICO - CÍVEL,ASSISTENTE JURÍDICO -,DATA AUDIENCIA INICIAL,RECLAMAÇÃO BLACK FRIDAY?,OUTRAS PARTES / NÃO-CLIENTES,MOTIVO DA CRITICIDADE,ADVOGADO DA PARTE CONTRÁRIA,DATA DE REABERTURA,DATA DE RECEBIMENTO,PARTE DESCRITA NA INICIAL,TIPO DE CONTINGÊNCIA,ANO DA BLACK FRIDAY,DATA DA ÚLTIMA MOVIMENTAÇÃO PROCESSUAL,OBSERVAÇÕES,OBSERVAÇÃO,TERCEIRO SOLVENTE,INCONTROVERSO (ZERAR PROVISÃO),RESULTADO,DATA DE SOLICITAÇÃO DE ENCERRAMENTO,DATA DE ENCERRAMENTO NO TRIBUNAL,MOTIVO DE ENCERRAMENTO,RECLAMAÇÃO ANTERIOR NO PROCON?,DATA DE REGISTRO DO ENCERRAMENTO,EXISTE PROCESSO COM O MESMO CPF?,CÍVEL MASSA - RESPONSABILIDADE,ESTRATÉGIA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,JUSTIFICATIVA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,CÍVEL MASSA - TIPOS DE TERCEIRO,PARTE CONTRÁRIA DATA ADMISSÃO,PARTE CONTRÁRIA DATA DISPENSA,PARTE CONTRÁRIA - STATUS EM FOLHA,PARTE CONTRÁRIA - MATRICULA,PARTE CONTRÁRIA - CARGO - CARGO (GRUPO),MOTIVO DA BAIXA PROVISÓRIA,PRODUTO,FABRICANTE DO PRODUTO,VALOR DO PRODUTO,PROCESSO - Nº. PEDIDO,DATA DO PEDIDO,LISTA LOJISTA - NOME,LISTA LOJISTA - ID,DATA DA COMPRA,TRANSPORTADORA,NÚMERO DA NOTA FISCAL,SITE DA COMPRA,DATA DO FATO GERADOR,DATA FATO GERADOR,DATA DO FATO GERADOR.1,DATA DO FATO GERADOR.2,INDIQUE A FILIAL,Data da Baixa Provisória,DATA DE REATIVAÇÃO - nativo,DATA DA REATIVAÇÃO -,E-MAIL - PARTE CONTRÁRIA,Processo - RESPONSÁVEL PELA VALIDAÇÃO - AUTOMÁTICO,Processo - RESPONSÁVEL PELA VALIDAÇÃO - MANUAL,PARA QUAL STATUS DESEJA ALTERAR?,MOTIVO DA ALTERAÇÃO DE STATUS,APTO PARA ACORDO?,ILEGITIMIDADE PASSIVA,PROJETO RECORTE MASSA?,Processo - EVENTO - CÍVEL,Processo - POSSUI A INICIAL?,Processo - CARTEIRA ESTRATÉGICO - CIVEL,Processo - MOTIVO DA APTIDÃO ?,PROCESSO - VIA NO POLO,PROCESSO - OBJETO CÍVEL (2) - NEW - SECUNDÁRIO,PROCESSO - OBJETO CÍVEL (2) - NEW - ASSUNTO,FEIRÃO LIMPA NOME,DESENROLA BRASIL,SUBSÍDIOS DISPONIBILIZADOS ATÉ O MOMENTO DE INSERÇÃO DA DEFESA?,APRESENTADA DEFESA GENÉRICA?,CATEGORIZAÇÃO BANQI,GRUPO CASAS BAHIA NO POLO DA AÇÃO?,Processo - DATA DA ABERTURA DE CONTA,PAGAR HONORÁRIOS AO ESCRITÓRIO?,Pedido,ADVOGADO OFENSOR (CÍV. MASSA),CÍVEL MASSA - FLUXO DE RESSARCIMENTO?,SEGUIR COM O PAGAMENTO DE HONORARIOS,DATA DO ACEITE,STATUS_1,Nova_Coluna,CHAVE_ID_STATUS
0,289797,CIV.23267,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),ENTREGA E MONTAGEM,ENTREGA DE PRODUTO DIVERSO - EM,2016-06-07,BAIXA PROVISORIA,2114013051.00,GRUPO CASAS BAHIA S/A,FELIPPE SILVA FOGAZZA,21720.00,JUDICIAL,RJ,NOVA IGUAÇÚ,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,7ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-05-14,'00505448220148190038,KEROLLYN DE OLIVEIRA VIRLA,N/I,LAURO RABHA,NaN,CUMPRIMENTO DE SENTENÇA,NaN,GUILHERME SPAMER,2024-07-08 14:49:15.126,NaT,0,0.00,NÃO,NAYARA CARLA DE SOUSA,LEONARDO PAULO LOMBARDI RODRIGUES - CNOVA,NaN,NaN,ADVOGADO ADVERSO - TATIANA BASTOS DE MELLO,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,NaT,NaN,PASSIVO,NaN,NaT,NaN,PROCESSOS ENCERRADOS POR BANCO CONFORME ANALISE FEITA EM PLANILHA ENVIADA A GERENCIA DO PLANEJAM...,NaN,NaN,PARCIALMENTE PROCEDENTE,2019-04-12 00:00:00,2020-11-04,CONDENAÇÃO COM OBF E PAGAMENTO,NaN,2020-11-04,NaN,NaN,ACORDO,DECISÃO DESFAVORÁVEL,LEGADO,NaT,NaT,NaN,NaN,NaN,NaN,ARMÁRIO MULTIUSO,BARTIRA,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2024-07-08 14:49:15.126,NaN,NaT,NaN,NaN,NaN,2 - DE ENCERRADO PARA BAIXA PROVISÓRIA,CUSTAS REMANESCENTE,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,2024-12-06 00:00:00,,289797ENCERRADOLAURO RABHA,NaN
1,317446,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,JEC,MASSA (CÍVEL),VENDA DE CARTEIRA DE CRÉDITO,VENDA DE CARTEIRA DE CRÉDITO - VCC,2016-10-13,BAIXA PROVISORIA,2106503025.00,GLOBEX UTILIDADES S/A (GPA),FELIPPE SILVA FOGAZZA,40000.00,JUDICIAL,RJ,RIO DE JANEIRO,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,20ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-09-16,00176673020158190208,MARCELO PASCHOAL DE OLIVEIRA,068.477.487-96,LAURO RABHA,QUEIROZ E LAUTENSCHLAGER (CÍVEL),RECURSAL,NÃO SE APLICA,YNAIA OLIVEIRA DA SILVA - CNOVA,2021-06-28 00:00:00.000,NaT,0,0.00,NÃO,NAYARA CARLA DE SOUSA,LEONARDO PAULO LOMBARDI RODRIGUES - CNOVA,2016-10-18 14:20:00,NÃO,NaN,NaN,RENATO FRANCISCO DA SILVA NETO,2018-08-29 20:06:09.910,2016-10-03,NaN,PASSIVO,NaN,NaT,NaN,NaN,NÃO SE APLICA,NaN,NaN,2019-10-04 14:46:39,NaT,NaN,NÃO,NaT,NaN,NaN,ACORDO,DECISÃO DESFAVORÁVEL,VENDA DE CARTEIRA DE CRÉDITO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,NaT,NaN,NaN,NaN,NaN,NaT,1998-10-25,NaN,NaN,2021-06-28 00:00:00.000,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DANOS MORAIS,NaN,NaN,NÃO SE APLICA,2024-12-06 00:00:00,,317446ENCERRADOLAURO RABHA,NaN
2,290822,CIV.24393,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),VÍCIO DO PRODUTO,PRODUTO DE TERCEIROS,2016-08-29,REATIVADO,2112003054.00,GRUPO CASAS BAHIA S/A,ROBERTA LUANA ROCHA,116694.50,JUDICIAL,BA,JUAZEIRO,TRIBUNAL DE JUSTIÇA DO ESTADO DA BAHIA,2ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-08-15,'09618686420158050146,MARIA SANDRA LIMA SILVA,N/I,QUEIROZ CAVALCANTI ADVOGADOS,NaN,CONHECIMENTO,NaN,GUILHERME SPAMER,2024-04-09 16:45:28.054,NaT,3168,5069.59,NÃO,GABRIEL GALDINO DE OLIVEIRA,MARIANA LAMEIRA E SILVA,NaN,NaN,NaN,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,NaT,NaN,PASSIVO,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NaN,CASAS BAHIA,ACORDO,AUSÊNCIA DE SUBSÍDIOS,FORNECEDOR,NaT,NaT,NaN,NaN,NaN,PAGAMENTO,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2024-04-09 16:45:28.054,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,ESTRATÉGIA,NaN,NaN,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,2024-12-18 00:00:00,,290822ENCERRADOQUEIROZ CAVALCANTI ADVOGADOS,NaN
3,84996,JEC.217184GPA,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,JEC,MASSA (CÍVEL),ENTREGA E MONTAGEM,AUSÊNCIA DE ENTREGA - EM,2016-06-09,REATIVADO,2117920206.00,CASAS BAHIA ONLINE,ROBERTA LUANA ROCHA,807.04,JUDICIAL,AL,IGREJA NOVA,TRIBUNAL DE JUSTIÇA DO ESTADO DE ALAGOAS,JEC,AÇÃO DE INDENIZAÇÃO,2016-02-18,0700251-79.2015.8.02.0014,JOE JANIO DE OLIVEIRA DAVINO,055.833.364-80,QUEIROZ CAVALCANTI ADVOGADOS,NaN,EXECUÇÃO,MARKETPLACE,GUILHERME SPAMER,2018-05-23 00:00:00.000,NaT,3913,6261.78,NÃO,GABRIEL GALDINO DE OLIVEIRA,MARIANA LAMEIRA E SILVA,NaN,NÃO,NaN,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,2024-04-23,NaN,PASSIVO,NaN,NaT,NaN,NaN,NÃO SE APLICA,NaN,AUSÊNCIA DO AUTOR,NaT,2018-05-23,AUSÊNCIA DO AUTOR,NaN,NaT,NÃO,NaN,ACORDO,AUSÊNCIA DE SUBSÍDIOS,NÃO É TERCEIRO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2018-05-23 00:00:00.000,NaN,2024-04-15 18:19:25.459,NaN,NaN,NaN,4 - DE ENCERRADO PARA REATIVADO,4.1 - EXECUÇÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,SIM,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,2024-12-18 00:00:00,,84996ENCERRADOQUEIROZ CAVALCANTI ADVOGADOS,NaN
4,305154,JEC.222054,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),CRÉDITO E COBRANÇA,CARTÃO PF - COBRANÇA INDEVIDA COM NEGATIVAÇÃO,2016-05-31,REATIVADO,2106500311.00,GRUPO CASAS BAHIA S/A,JENIFFER CONCEICAO DE SOUZA,3006.80,JUDICIAL,SC,JOINVILLE,TRIBUNAL DE JUSTIÇA DO ESTADO DE SANTA CATARINA,2ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2015-09-08,0017211-67.2015.8.24.0038,VERA LUCIA CALVO,491.659.179-87,PINTO & SOARES ADVOGADOS ASSOCIADOS,NaN,CONHECIMENTO,DIRETA,GUILHERME SPAMER,NaT,NaT,0,0.00,NÃO,RAFAEL EPISCOPO RODRIGUES COSTA,WEVERTON SOUZA MATOS,NaN,NÃO,TERCEIRO - BANCO ITAUCRED,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,2019-10-23,VIA VAREJO,PASSIVO,NaN,NaT,NaN,NaN,ITAÚ,NaN,SANEAMENTO - MENDES E BARRETO,NaT,2025-06-27,SANEAMENTO - MENDES E BARRETO,NÃO,NaT,NaN,TERCEIROS,ACORDO,DECISÃO DESFAVORÁVEL,CARTÃO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,NaT,NaN,NaN,NaN,NaN,NaT,2015-09-08,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,SIM,NÃO,NaN,NaN,NaN,NaN,ESTRATÉGIA,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM,NÃO SE APLICA,2024-12-04 00:00:00,,305154ENCERRADOPINTO & SOARES ADVOGADOS ASSOCIADOS,NaN

In [0]:
#Dropa as duplicada do vaturamento antigo
df_fatu_hist_old['Chave (ID + STATUS)_1'] = df_fatu_hist_old['Chave (ID + STATUS)']

In [0]:
#Realiza o map e grava nas linhas vazias do CHAVE_ID_STATUS 
df_fatu_hist_old = df_fatu_hist_old.drop_duplicates(subset=['Chave (ID + STATUS)'], keep='last')

mapa_old = df_fatu_hist_old.set_index('Chave (ID + STATUS)')['Chave (ID + STATUS)_1']

df_ger_1['CHAVE_ID_STATUS'] = df_ger_1['CHAVE_ID_STATUS'].fillna(
    df_ger_1['Nova_Coluna'].map(mapa_old)
)

In [0]:
#Aplica a condição de escrita na coluna STATUS_1
cond2 = df_ger_1['CHAVE_ID_STATUS'].notnull() & df_ger_1['Nova_Coluna'].notnull()
df_ger_1.loc[cond2, 'STATUS_1'] = 'Não Faturar - Encerramento pago em outro faturamento'

#dropa as colunas criadas para validação
df_ger_1 = df_ger_1.drop(columns=['Nova_Coluna', 'CHAVE_ID_STATUS'])

In [0]:
df_ger_1.head()

,PROCESSO - ID,PASTA,GRUPO,ÁREA DO DIREITO,SUB-ÁREA DO DIREITO,ESTEIRA,ASSUNTO (CÍVEL) - PRINCIPAL,ASSUNTO (CÍVEL) - ASSUNTO,DATA REGISTRADO,STATUS,CENTRO DE CUSTO / ÁREA DEMANDANTE - CÓDIGO,EMPRESA,ADVOGADO RESPONSÁVEL,VALOR DA CAUSA,ESFERA,ESTADO,COMARCA,FORO/TRIBUNAL/ÓRGÃO,VARA/ÓRGÃO,AÇÃO,DISTRIBUIÇÃO,NÚMERO DO PROCESSO,PARTE CONTRÁRIA NOME,PARTE CONTRÁRIA CPF,ESCRITÓRIO EXTERNO,Escritório Anterior,FASE,COMPRA DIRETA OU MARKETPLACE? - NEW,USUÁRIO CADASTRANTE,DATA DA BAIXA PROVISÓRIA,DATA DA REATIVAÇÃO,VALOR PROVISIONADO,VALOR PROVISIONADO ATUALIZADO,PROCESSO CRITICO? (CÍVEL),ASSISTENTE JURÍDICO - CÍVEL,ASSISTENTE JURÍDICO -,DATA AUDIENCIA INICIAL,RECLAMAÇÃO BLACK FRIDAY?,OUTRAS PARTES / NÃO-CLIENTES,MOTIVO DA CRITICIDADE,ADVOGADO DA PARTE CONTRÁRIA,DATA DE REABERTURA,DATA DE RECEBIMENTO,PARTE DESCRITA NA INICIAL,TIPO DE CONTINGÊNCIA,ANO DA BLACK FRIDAY,DATA DA ÚLTIMA MOVIMENTAÇÃO PROCESSUAL,OBSERVAÇÕES,OBSERVAÇÃO,TERCEIRO SOLVENTE,INCONTROVERSO (ZERAR PROVISÃO),RESULTADO,DATA DE SOLICITAÇÃO DE ENCERRAMENTO,DATA DE ENCERRAMENTO NO TRIBUNAL,MOTIVO DE ENCERRAMENTO,RECLAMAÇÃO ANTERIOR NO PROCON?,DATA DE REGISTRO DO ENCERRAMENTO,EXISTE PROCESSO COM O MESMO CPF?,CÍVEL MASSA - RESPONSABILIDADE,ESTRATÉGIA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,JUSTIFICATIVA - DEFINIR ESTRATÉGIA DE ATUAÇÃO E JUSTIFICATIVA,CÍVEL MASSA - TIPOS DE TERCEIRO,PARTE CONTRÁRIA DATA ADMISSÃO,PARTE CONTRÁRIA DATA DISPENSA,PARTE CONTRÁRIA - STATUS EM FOLHA,PARTE CONTRÁRIA - MATRICULA,PARTE CONTRÁRIA - CARGO - CARGO (GRUPO),MOTIVO DA BAIXA PROVISÓRIA,PRODUTO,FABRICANTE DO PRODUTO,VALOR DO PRODUTO,PROCESSO - Nº. PEDIDO,DATA DO PEDIDO,LISTA LOJISTA - NOME,LISTA LOJISTA - ID,DATA DA COMPRA,TRANSPORTADORA,NÚMERO DA NOTA FISCAL,SITE DA COMPRA,DATA DO FATO GERADOR,DATA FATO GERADOR,DATA DO FATO GERADOR.1,DATA DO FATO GERADOR.2,INDIQUE A FILIAL,Data da Baixa Provisória,DATA DE REATIVAÇÃO - nativo,DATA DA REATIVAÇÃO -,E-MAIL - PARTE CONTRÁRIA,Processo - RESPONSÁVEL PELA VALIDAÇÃO - AUTOMÁTICO,Processo - RESPONSÁVEL PELA VALIDAÇÃO - MANUAL,PARA QUAL STATUS DESEJA ALTERAR?,MOTIVO DA ALTERAÇÃO DE STATUS,APTO PARA ACORDO?,ILEGITIMIDADE PASSIVA,PROJETO RECORTE MASSA?,Processo - EVENTO - CÍVEL,Processo - POSSUI A INICIAL?,Processo - CARTEIRA ESTRATÉGICO - CIVEL,Processo - MOTIVO DA APTIDÃO ?,PROCESSO - VIA NO POLO,PROCESSO - OBJETO CÍVEL (2) - NEW - SECUNDÁRIO,PROCESSO - OBJETO CÍVEL (2) - NEW - ASSUNTO,FEIRÃO LIMPA NOME,DESENROLA BRASIL,SUBSÍDIOS DISPONIBILIZADOS ATÉ O MOMENTO DE INSERÇÃO DA DEFESA?,APRESENTADA DEFESA GENÉRICA?,CATEGORIZAÇÃO BANQI,GRUPO CASAS BAHIA NO POLO DA AÇÃO?,Processo - DATA DA ABERTURA DE CONTA,PAGAR HONORÁRIOS AO ESCRITÓRIO?,Pedido,ADVOGADO OFENSOR (CÍV. MASSA),CÍVEL MASSA - FLUXO DE RESSARCIMENTO?,SEGUIR COM O PAGAMENTO DE HONORARIOS,DATA DO ACEITE,STATUS_1
0,289797,CIV.23267,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),ENTREGA E MONTAGEM,ENTREGA DE PRODUTO DIVERSO - EM,2016-06-07,BAIXA PROVISORIA,2114013051.00,GRUPO CASAS BAHIA S/A,FELIPPE SILVA FOGAZZA,21720.00,JUDICIAL,RJ,NOVA IGUAÇÚ,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,7ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-05-14,'00505448220148190038,KEROLLYN DE OLIVEIRA VIRLA,N/I,LAURO RABHA,NaN,CUMPRIMENTO DE SENTENÇA,NaN,GUILHERME SPAMER,2024-07-08 14:49:15.126,NaT,0,0.00,NÃO,NAYARA CARLA DE SOUSA,LEONARDO PAULO LOMBARDI RODRIGUES - CNOVA,NaN,NaN,ADVOGADO ADVERSO - TATIANA BASTOS DE MELLO,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,NaT,NaN,PASSIVO,NaN,NaT,NaN,PROCESSOS ENCERRADOS POR BANCO CONFORME ANALISE FEITA EM PLANILHA ENVIADA A GERENCIA DO PLANEJAM...,NaN,NaN,PARCIALMENTE PROCEDENTE,2019-04-12 00:00:00,2020-11-04,CONDENAÇÃO COM OBF E PAGAMENTO,NaN,2020-11-04,NaN,NaN,ACORDO,DECISÃO DESFAVORÁVEL,LEGADO,NaT,NaT,NaN,NaN,NaN,NaN,ARMÁRIO MULTIUSO,BARTIRA,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2024-07-08 14:49:15.126,NaN,NaT,NaN,NaN,NaN,2 - DE ENCERRADO PARA BAIXA PROVISÓRIA,CUSTAS REMANESCENTE,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,2024-12-06 00:00:00,
1,317446,NaN,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,JEC,MASSA (CÍVEL),VENDA DE CARTEIRA DE CRÉDITO,VENDA DE CARTEIRA DE CRÉDITO - VCC,2016-10-13,BAIXA PROVISORIA,2106503025.00,GLOBEX UTILIDADES S/A (GPA),FELIPPE SILVA FOGAZZA,40000.00,JUDICIAL,RJ,RIO DE JANEIRO,TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO,20ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-09-16,00176673020158190208,MARCELO PASCHOAL DE OLIVEIRA,068.477.487-96,LAURO RABHA,QUEIROZ E LAUTENSCHLAGER (CÍVEL),RECURSAL,NÃO SE APLICA,YNAIA OLIVEIRA DA SILVA - CNOVA,2021-06-28 00:00:00.000,NaT,0,0.00,NÃO,NAYARA CARLA DE SOUSA,LEONARDO PAULO LOMBARDI RODRIGUES - CNOVA,2016-10-18 14:20:00,NÃO,NaN,NaN,RENATO FRANCISCO DA SILVA NETO,2018-08-29 20:06:09.910,2016-10-03,NaN,PASSIVO,NaN,NaT,NaN,NaN,NÃO SE APLICA,NaN,NaN,2019-10-04 14:46:39,NaT,NaN,NÃO,NaT,NaN,NaN,ACORDO,DECISÃO DESFAVORÁVEL,VENDA DE CARTEIRA DE CRÉDITO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,NaT,NaN,NaN,NaN,NaN,NaT,1998-10-25,NaN,NaN,2021-06-28 00:00:00.000,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DANOS MORAIS,NaN,NaN,NÃO SE APLICA,2024-12-06 00:00:00,
2,290822,CIV.24393,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),VÍCIO DO PRODUTO,PRODUTO DE TERCEIROS,2016-08-29,REATIVADO,2112003054.00,GRUPO CASAS BAHIA S/A,ROBERTA LUANA ROCHA,116694.50,JUDICIAL,BA,JUAZEIRO,TRIBUNAL DE JUSTIÇA DO ESTADO DA BAHIA,2ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2016-08-15,'09618686420158050146,MARIA SANDRA LIMA SILVA,N/I,QUEIROZ CAVALCANTI ADVOGADOS,NaN,CONHECIMENTO,NaN,GUILHERME SPAMER,2024-04-09 16:45:28.054,NaT,3168,5069.59,NÃO,GABRIEL GALDINO DE OLIVEIRA,MARIANA LAMEIRA E SILVA,NaN,NaN,NaN,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,NaT,NaN,PASSIVO,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaT,NaN,CASAS BAHIA,ACORDO,AUSÊNCIA DE SUBSÍDIOS,FORNECEDOR,NaT,NaT,NaN,NaN,NaN,PAGAMENTO,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2024-04-09 16:45:28.054,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,ESTRATÉGIA,NaN,NaN,NaN,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,2024-12-18 00:00:00,
3,84996,JEC.217184GPA,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,JEC,MASSA (CÍVEL),ENTREGA E MONTAGEM,AUSÊNCIA DE ENTREGA - EM,2016-06-09,REATIVADO,2117920206.00,CASAS BAHIA ONLINE,ROBERTA LUANA ROCHA,807.04,JUDICIAL,AL,IGREJA NOVA,TRIBUNAL DE JUSTIÇA DO ESTADO DE ALAGOAS,JEC,AÇÃO DE INDENIZAÇÃO,2016-02-18,0700251-79.2015.8.02.0014,JOE JANIO DE OLIVEIRA DAVINO,055.833.364-80,QUEIROZ CAVALCANTI ADVOGADOS,NaN,EXECUÇÃO,MARKETPLACE,GUILHERME SPAMER,2018-05-23 00:00:00.000,NaT,3913,6261.78,NÃO,GABRIEL GALDINO DE OLIVEIRA,MARIANA LAMEIRA E SILVA,NaN,NÃO,NaN,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,2024-04-23,NaN,PASSIVO,NaN,NaT,NaN,NaN,NÃO SE APLICA,NaN,AUSÊNCIA DO AUTOR,NaT,2018-05-23,AUSÊNCIA DO AUTOR,NaN,NaT,NÃO,NaN,ACORDO,AUSÊNCIA DE SUBSÍDIOS,NÃO É TERCEIRO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,2018-05-23 00:00:00.000,NaN,2024-04-15 18:19:25.459,NaN,NaN,NaN,4 - DE ENCERRADO PARA REATIVADO,4.1 - EXECUÇÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,SIM,NaN,NaN,NaN,NaN,NaN,NÃO SE APLICA,2024-12-18 00:00:00,
4,305154,JEC.222054,GRUPO CASAS BAHIA S/A,CÍVEL MASSA,VARA COMUM,MASSA (CÍVEL),CRÉDITO E COBRANÇA,CARTÃO PF - COBRANÇA INDEVIDA COM NEGATIVAÇÃO,2016-05-31,REATIVADO,2106500311.00,GRUPO CASAS BAHIA S/A,JENIFFER CONCEICAO DE SOUZA,3006.80,JUDICIAL,SC,JOINVILLE,TRIBUNAL DE JUSTIÇA DO ESTADO DE SANTA CATARINA,2ª VARA CÍVEL,AÇÃO DE INDENIZAÇÃO,2015-09-08,0017211-67.2015.8.24.0038,VERA LUCIA CALVO,491.659.179-87,PINTO & SOARES ADVOGADOS ASSOCIADOS,NaN,CONHECIMENTO,DIRETA,GUILHERME SPAMER,NaT,NaT,0,0.00,NÃO,RAFAEL EPISCOPO RODRIGUES COSTA,WEVERTON SOUZA MATOS,NaN,NÃO,TERCEIRO - BANCO ITAUCRED,NaN,SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF,NaT,2019-10-23,VIA VAREJO,PASSIVO,NaN,NaT,NaN,NaN,ITAÚ,NaN,SANEAMENTO - MENDES E BARRETO,NaT,2025-06-27,SANEAMENTO - MENDES E BARRETO,NÃO,NaT,NaN,TERCEIROS,ACORDO,DECISÃO DESFAVORÁVEL,CARTÃO,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaT,NÃO SE APLICA,NÃO SE APLICA,NaT,NaN,NaN,NaN,NaN,NaT,2015-09-08,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,SIM,NÃO,NaN,NaN,NaN,NaN,ESTRATÉGIA,NaN,NÃO SE APLICA,NÃO SE APLICA,NÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIM,NÃO SE APLICA,2024-12-04 00:00:00,

In [0]:
#Condição de não faturar Zurick e Faturar o restante que foi null 
cond3 = df_ger_1['SEGUIR COM O PAGAMENTO DE HONORARIOS'] == 'NÃO'
df_ger_1.loc[cond3, 'STATUS_1'] = 'Não Faturar - Zurick'

# A condição correta para encontrar CÉLULAS VAZIAS (strings vazias)
cond4 = df_ger_1['STATUS_1'] == ''

# O resto do seu código está perfeito e vai funcionar com a condição correta
df_ger_1.loc[cond4, 'STATUS_1'] = 'Faturar'

In [0]:
# Mostra um array com cada valor único que existe na coluna 'STATUS'
valores_unicos_status = df_ger_1['STATUS_1'].unique()

print("Valores únicos na coluna 'STATUS':")
print(valores_unicos_status)

Valores únicos na coluna 'STATUS':
['Faturar' 'Não Faturar - Encerramento pago em outro faturamento'
 'Não Faturar - Sem Data Aceite' 'Não Faturar - Zurick']

In [0]:
#Reordena as colunas para ficar igual ao original

reordena_colunas = df_ger_1.columns.to_list()
reordena_colunas.remove('STATUS_1')
reordena_colunas.insert(0, 'STATUS_1')
reordena_colunas.remove('DATA DO ACEITE')
reordena_colunas.insert(10,'DATA DO ACEITE')

df_ger_1 = df_ger_1[reordena_colunas]

In [0]:
df_ger_1.columns

Index(['STATUS_1', 'PROCESSO - ID', 'PASTA', 'GRUPO', 'ÁREA DO DIREITO',
       'SUB-ÁREA DO DIREITO', 'ESTEIRA', 'ASSUNTO (CÍVEL) - PRINCIPAL',
       'ASSUNTO (CÍVEL) - ASSUNTO', 'DATA REGISTRADO',
       ...
       'SUBSÍDIOS DISPONIBILIZADOS ATÉ O MOMENTO DE INSERÇÃO DA DEFESA?',
       'APRESENTADA DEFESA GENÉRICA?', 'CATEGORIZAÇÃO BANQI',
       'GRUPO CASAS BAHIA NO POLO DA AÇÃO?',
       'Processo - DATA DA ABERTURA DE CONTA',
       'PAGAR HONORÁRIOS AO ESCRITÓRIO?', 'Pedido',
       'ADVOGADO OFENSOR (CÍV. MASSA)',
       'CÍVEL MASSA - FLUXO DE RESSARCIMENTO?',
       'SEGUIR COM O PAGAMENTO DE HONORARIOS'],
      dtype='object', length=116)

In [0]:
colunas_para_manter = [
    'STATUS_1', 'PROCESSO - ID', 'PASTA', 'GRUPO', 'ÁREA DO DIREITO',
    'SUB-ÁREA DO DIREITO', 'ESTEIRA', 'ASSUNTO (CÍVEL) - PRINCIPAL',
    'ASSUNTO (CÍVEL) - ASSUNTO', 'DATA REGISTRADO', 'DATA DO ACEITE', 'STATUS',
    'CENTRO DE CUSTO / ÁREA DEMANDANTE - CÓDIGO', 'EMPRESA',
    'ADVOGADO RESPONSÁVEL', 'VALOR DA CAUSA', 'ESFERA', 'ESTADO', 'COMARCA',
    'FORO/TRIBUNAL/ÓRGÃO', 'VARA/ÓRGÃO', 'AÇÃO', 'DISTRIBUIÇÃO',
    'NÚMERO DO PROCESSO', 'PARTE CONTRÁRIA NOME', 'PARTE CONTRÁRIA CPF',
    'ESCRITÓRIO EXTERNO', 'Escritório Anterior', 'FASE',
    'COMPRA DIRETA OU MARKETPLACE? - NEW ', 'USUÁRIO CADASTRANTE',
    'DATA DA BAIXA PROVISÓRIA', 'DATA DA REATIVAÇÃO', 'VALOR PROVISIONADO',
    'VALOR PROVISIONADO ATUALIZADO', 'PROCESSO CRITICO? (CÍVEL)',
    'ASSISTENTE JURÍDICO - CÍVEL', 'ASSISTENTE JURÍDICO -',
    'DATA AUDIENCIA INICIAL', 'RECLAMAÇÃO BLACK FRIDAY?',
    'OUTRAS PARTES / NÃO-CLIENTES', 'MOTIVO DA CRITICIDADE',
    'ADVOGADO DA PARTE CONTRÁRIA', 'DATA DE REABERTURA',
    'DATA DE RECEBIMENTO', 'PARTE DESCRITA NA INICIAL',
    'TIPO DE CONTINGÊNCIA', 'ANO DA BLACK FRIDAY',
    'DATA DA ÚLTIMA MOVIMENTAÇÃO PROCESSUAL', 'OBSERVAÇÕES', 'OBSERVAÇÃO',
    'TERCEIRO SOLVENTE', 'INCONTROVERSO (ZERAR PROVISÃO)', 'RESULTADO',
    'DATA DE SOLICITAÇÃO DE ENCERRAMENTO',
    'DATA DE ENCERRAMENTO NO TRIBUNAL', 'MOTIVO DE ENCERRAMENTO ',
    'RECLAMAÇÃO ANTERIOR NO PROCON?', 'DATA DE REGISTRO DO ENCERRAMENTO',
    'EXISTE PROCESSO COM O MESMO CPF?', 'CÍVEL MASSA - RESPONSABILIDADE',
    'CÍVEL MASSA - TIPOS DE TERCEIRO',
    'SEGUIR COM O PAGAMENTO DE HONORARIOS'
]

# 2. Crie um novo DataFrame que é uma "fatia" do original, 
df_ger_1 = df_ger_1[colunas_para_manter]

# Agora, 'df_filtrado' contém APENAS as colunas que você listou.
print(df_ger_1.head())

  STATUS_1  PROCESSO - ID          PASTA                  GRUPO  \
0  Faturar         289797      CIV.23267  GRUPO CASAS BAHIA S/A
1  Faturar         317446            NaN  GRUPO CASAS BAHIA S/A
2  Faturar         290822      CIV.24393  GRUPO CASAS BAHIA S/A
3  Faturar          84996  JEC.217184GPA  GRUPO CASAS BAHIA S/A
4  Faturar         305154     JEC.222054  GRUPO CASAS BAHIA S/A

  ÁREA DO DIREITO SUB-ÁREA DO DIREITO        ESTEIRA  \
0     CÍVEL MASSA          VARA COMUM  MASSA (CÍVEL)
1     CÍVEL MASSA                 JEC  MASSA (CÍVEL)
2     CÍVEL MASSA          VARA COMUM  MASSA (CÍVEL)
3     CÍVEL MASSA                 JEC  MASSA (CÍVEL)
4     CÍVEL MASSA          VARA COMUM  MASSA (CÍVEL)

    ASSUNTO (CÍVEL) - PRINCIPAL  \
0            ENTREGA E MONTAGEM
1  VENDA DE CARTEIRA DE CRÉDITO
2              VÍCIO DO PRODUTO
3            ENTREGA E MONTAGEM
4            CRÉDITO E COBRANÇA

                       ASSUNTO (CÍVEL) - ASSUNTO DATA REGISTRADO  \
0                ENTREGA DE PRODUTO DIVERSO - EM      2016-06-07
1             VENDA DE CARTEIRA DE CRÉDITO - VCC      2016-10-13
2                           PRODUTO DE TERCEIROS      2016-08-29
3                       AUSÊNCIA DE ENTREGA - EM      2016-06-09
4  CARTÃO PF - COBRANÇA INDEVIDA COM NEGATIVAÇÃO      2016-05-31

        DATA DO ACEITE            STATUS  \
0  2024-12-06 00:00:00  BAIXA PROVISORIA
1  2024-12-06 00:00:00  BAIXA PROVISORIA
2  2024-12-18 00:00:00         REATIVADO
3  2024-12-18 00:00:00         REATIVADO
4  2024-12-04 00:00:00         REATIVADO

   CENTRO DE CUSTO / ÁREA DEMANDANTE - CÓDIGO                      EMPRESA  \
0                               2114013051.00        GRUPO CASAS BAHIA S/A
1                               2106503025.00  GLOBEX UTILIDADES S/A (GPA)
2                               2112003054.00        GRUPO CASAS BAHIA S/A
3                               2117920206.00           CASAS BAHIA ONLINE
4                               2106500311.00        GRUPO CASAS BAHIA S/A

          ADVOGADO RESPONSÁVEL  VALOR DA CAUSA    ESFERA ESTADO  \
0        FELIPPE SILVA FOGAZZA        21720.00  JUDICIAL     RJ
1        FELIPPE SILVA FOGAZZA        40000.00  JUDICIAL     RJ
2          ROBERTA LUANA ROCHA       116694.50  JUDICIAL     BA
3          ROBERTA LUANA ROCHA          807.04  JUDICIAL     AL
4  JENIFFER CONCEICAO DE SOUZA         3006.80  JUDICIAL     SC

          COMARCA                              FORO/TRIBUNAL/ÓRGÃO  \
0     NOVA IGUAÇÚ  TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO
1  RIO DE JANEIRO  TRIBUNAL DE JUSTIÇA DO ESTADO DO RIO DE JANEIRO
2        JUAZEIRO           TRIBUNAL DE JUSTIÇA DO ESTADO DA BAHIA
3     IGREJA NOVA         TRIBUNAL DE JUSTIÇA DO ESTADO DE ALAGOAS
4       JOINVILLE  TRIBUNAL DE JUSTIÇA DO ESTADO DE SANTA CATARINA

       VARA/ÓRGÃO                 AÇÃO DISTRIBUIÇÃO  \
0   7ª VARA CÍVEL  AÇÃO DE INDENIZAÇÃO   2016-05-14
1  20ª VARA CÍVEL  AÇÃO DE INDENIZAÇÃO   2016-09-16
2   2ª VARA CÍVEL  AÇÃO DE INDENIZAÇÃO   2016-08-15
3             JEC  AÇÃO DE INDENIZAÇÃO   2016-02-18
4   2ª VARA CÍVEL  AÇÃO DE INDENIZAÇÃO   2015-09-08

          NÚMERO DO PROCESSO           PARTE CONTRÁRIA NOME  \
0      '00505448220148190038     KEROLLYN DE OLIVEIRA VIRLA
1       00176673020158190208  MARCELO PASCHOAL DE OLIVEIRA
2      '09618686420158050146        MARIA SANDRA LIMA SILVA
3  0700251-79.2015.8.02.0014   JOE JANIO DE OLIVEIRA DAVINO
4  0017211-67.2015.8.24.0038               VERA LUCIA CALVO

  PARTE CONTRÁRIA CPF                   ESCRITÓRIO EXTERNO  \
0                 N/I                          LAURO RABHA
1      068.477.487-96                          LAURO RABHA
2                 N/I         QUEIROZ CAVALCANTI ADVOGADOS
3      055.833.364-80         QUEIROZ CAVALCANTI ADVOGADOS
4      491.659.179-87  PINTO & SOARES ADVOGADOS ASSOCIADOS

                Escritório Anterior                     FASE  \
0                               NaN  CUMPRIMENTO DE SENTENÇA
1  QUEIROZ E LAUTENSCHLAGER (CÍVEL)                 RECURSAL
2                               NaN             CONHECIMENTO
3                               NaN                 EXECUÇÃO
4                               NaN             CONHECIMENTO

  COMPRA DIRETA OU MARKETPLACE? - NEW               USUÁRIO CADASTRANTE  \
0                                  NaN                 GUILHERME SPAMER
1                        NÃO SE APLICA  YNAIA OLIVEIRA DA SILVA - CNOVA
2                                  NaN                 GUILHERME SPAMER
3                          MARKETPLACE                 GUILHERME SPAMER
4                               DIRETA                 GUILHERME SPAMER

  DATA DA BAIXA PROVISÓRIA DATA DA REATIVAÇÃO  VALOR PROVISIONADO  \
0  2024-07-08 14:49:15.126                NaT                   0
1  2021-06-28 00:00:00.000                NaT                   0
2  2024-04-09 16:45:28.054                NaT                3168
3  2018-05-23 00:00:00.000                NaT                3913
4                      NaT                NaT                   0

   VALOR PROVISIONADO ATUALIZADO PROCESSO CRITICO? (CÍVEL)  \
0                           0.00                       NÃO
1                           0.00                       NÃO
2                        5069.59                       NÃO
3                        6261.78                       NÃO
4                           0.00                       NÃO

       ASSISTENTE JURÍDICO - CÍVEL                      ASSISTENTE JURÍDICO -  \
0            NAYARA CARLA DE SOUSA  LEONARDO PAULO LOMBARDI RODRIGUES - CNOVA
1            NAYARA CARLA DE SOUSA  LEONARDO PAULO LOMBARDI RODRIGUES - CNOVA
2      GABRIEL GALDINO DE OLIVEIRA                    MARIANA LAMEIRA E SILVA
3      GABRIEL GALDINO DE OLIVEIRA                    MARIANA LAMEIRA E SILVA
4  RAFAEL EPISCOPO RODRIGUES COSTA                       WEVERTON SOUZA MATOS

  DATA AUDIENCIA INICIAL RECLAMAÇÃO BLACK FRIDAY?  \
0                    NaN                      NaN
1    2016-10-18 14:20:00                      NÃO
2                    NaN                      NaN
3                    NaN                      NÃO
4                    NaN                      NÃO

                 OUTRAS PARTES / NÃO-CLIENTES MOTIVO DA CRITICIDADE  \
0  ADVOGADO ADVERSO - TATIANA BASTOS DE MELLO                   NaN
1                                         NaN                   NaN
2                                         NaN                   NaN
3                                         NaN                   NaN
4                  TERCEIRO - BANCO ITAUCRED                    NaN

               ADVOGADO DA PARTE CONTRÁRIA      DATA DE REABERTURA  \
0  SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF                     NaT
1          RENATO FRANCISCO DA SILVA NETO  2018-08-29 20:06:09.910
2  SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF                     NaT
3  SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF                     NaT
4  SEM ADVOGADO - NÃO HÁ INDEFINIDO - . UF                     NaT

  DATA DE RECEBIMENTO PARTE DESCRITA NA INICIAL TIPO DE CONTINGÊNCIA  \
0                 NaT                       NaN              PASSIVO
1          2016-10-03                       NaN              PASSIVO
2                 NaT                       NaN              PASSIVO
3          2024-04-23                       NaN              PASSIVO
4          2019-10-23                VIA VAREJO              PASSIVO

   ANO DA BLACK FRIDAY DATA DA ÚLTIMA MOVIMENTAÇÃO PROCESSUAL OBSERVAÇÕES  \
0                  NaN                                    NaT         NaN
1                  NaN                                    NaT         NaN
2                  NaN                                    NaT         NaN
3                  NaN                                    NaT         NaN
4                  NaN                                    NaT         NaN

                                                                                            OBSERVAÇÃO  \
0  PROCESSOS ENCERRADOS POR BANCO CONFORME ANALISE FEITA EM PLANILHA ENVIADA A GERENCIA DO PLANEJAM...
1                                                                                                  NaN
2                                                                                                  NaN
3                                                                                                  NaN
4                                                                                                  NaN

  TERCEIRO SOLVENTE INCONTROVERSO (ZERAR PROVISÃO)  \
0               NaN                            NaN
1     NÃO SE APLICA                            NaN
2               NaN                            NaN
3     NÃO SE APLICA                            NaN
4              ITAÚ                            NaN

                       RESULTADO DATA DE SOLICITAÇÃO DE ENCERRAMENTO  \
0        PARCIALMENTE PROCEDENTE                 2019-04-12 00:00:00
1                            NaN                 2019-10-04 14:46:39
2                            NaN                                 NaT
3              AUSÊNCIA DO AUTOR                                 NaT
4  SANEAMENTO - MENDES E BARRETO                                 NaT

  DATA DE ENCERRAMENTO NO TRIBUNAL         MOTIVO DE ENCERRAMENTO   \
0                       2020-11-04  CONDENAÇÃO COM OBF E PAGAMENTO
1                              NaT                             NaN
2                              NaT                             NaN
3                       2018-05-23               AUSÊNCIA DO AUTOR
4                       2025-06-27   SANEAMENTO - MENDES E BARRETO

  RECLAMAÇÃO ANTERIOR NO PROCON? DATA DE REGISTRO DO ENCERRAMENTO  \
0                            NaN                       2020-11-04
1                            NÃO                              NaT
2                            NaN                              NaT
3                            NaN                              NaT
4                            NÃO                              NaT

  EXISTE PROCESSO COM O MESMO CPF? CÍVEL MASSA - RESPONSABILIDADE  \
0                              NaN                            NaN
1                              NaN                            NaN
2                              NaN                    CASAS BAHIA
3                              NÃO                            NaN
4                              NaN                      TERCEIROS

  CÍVEL MASSA - TIPOS DE TERCEIRO SEGUIR COM O PAGAMENTO DE HONORARIOS
0                          LEGADO                        NÃO SE APLICA
1    VENDA DE CARTEIRA DE CRÉDITO                        NÃO SE APLICA
2                      FORNECEDOR                        NÃO SE APLICA
3                  NÃO É TERCEIRO                        NÃO SE APLICA
4                          CARTÃO                        NÃO SE APLICA

In [0]:
import pandas as pd
from openpyxl import load_workbook
from openpyxl.utils.dataframe import dataframe_to_rows
from openpyxl.utils import get_column_letter
import shutil 

# --- CAMINHOS E NOMES ---
caminho_modelo = '/Volumes/databox/juridico_comum/arquivos/financeiro/Faturamento_Civel/Base_Gerencial_Modelo/CIVEL_GERENCIAL.xlsx'
caminho_final = '/Volumes/databox/juridico_comum/arquivos/financeiro/Faturamento_Civel/Gerencial_Consolidada_Final/'
nome_do_arquivo = f'BASE_GERENCIAL - {Mes}_Consolidada.xlsx'
caminho_saida = caminho_final + nome_do_arquivo

nome_da_planilha = 'CÍVEL' 

caminho_temporario = f'/tmp/{nome_do_arquivo}'

# --- LINHA INICIAL ---
linha_cabecalho = 6
linha_inicio_dados = linha_cabecalho + 1

try:
    workbook = load_workbook(caminho_modelo)
    
    sheet = workbook[nome_da_planilha]
    
    rows = dataframe_to_rows(df_ger_1, index=False, header=False)

    for r_idx, row in enumerate(rows, start=linha_inicio_dados):
        for c_idx, value in enumerate(row, start=1):
            sheet.cell(row=r_idx, column=c_idx, value=value)

    if sheet.auto_filter:
        max_col_letra = get_column_letter(sheet.max_column)
        novo_intervalo_filtro = f"A{linha_cabecalho}:{max_col_letra}{sheet.max_row}"
        sheet.auto_filter.ref = novo_intervalo_filtro

    # Etapa 1: Salvar no local temporário
    print(f"Salvando arquivo temporariamente em: {caminho_temporario}")
    workbook.save(caminho_temporario)

    # Etapa 2: Mover o arquivo para o destino final no Volume
    print(f"Movendo arquivo para o destino final: {caminho_saida}")
    shutil.move(caminho_temporario, caminho_saida)

    print("Arquivo salvo com sucesso no Databricks!")
    print(f"Caminho final: {caminho_saida}")

except Exception as e:
    print(f"Ocorreu um erro: {e}")

Salvando arquivo temporariamente em: /tmp/BASE_GERENCIAL - 20260218_Consolidada.xlsx
Movendo arquivo para o destino final: /Volumes/databox/juridico_comum/arquivos/financeiro/Faturamento_Civel/Gerencial_Consolidada_Final/BASE_GERENCIAL - 20260218_Consolidada.xlsx
Arquivo salvo com sucesso no Databricks!
Caminho final: /Volumes/databox/juridico_comum/arquivos/financeiro/Faturamento_Civel/Gerencial_Consolidada_Final/BASE_GERENCIAL - 20260218_Consolidada.xlsx

In [0]:
# CONDIÇÃO INVERSA: Contar quantas linhas SÃO 'Não Faturar - Sem Data Aceite'
#condicao_status_igual = df_ger_1['STATUS_1'] == 'Não Faturar - Sem Data Aceite'
#contagem_status_igual = condicao_status_igual.sum()

#print(f"Total de linhas onde o STATUS_1 É 'Não Faturar - Sem Data Aceite': {contagem_status_igual}")

In [0]:
#nulos_total = df_ger_1['DATA ACEITE'].isnull().sum()
#print(f'Total de linhas com nulos na coluna "DATA ACEITE": {nulos_total}')